import { Migration } from "@medusajs/framework/mikro-orm/migrations";

export class Migration20260207115801 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table if exists "purchase_order" drop constraint if exists "purchase_order_po_number_unique";`);
    this.addSql(`alter table if exists "payment_terms" drop constraint if exists "payment_terms_code_unique";`);
    this.addSql(`create table if not exists "approval_action" ("id" text not null, "approval_request_id" text not null, "step_number" integer not null, "step_name" text null, "action" text check ("action" in ('approve', 'reject', 'request_changes', 'escalate', 'skip')) not null, "action_by_id" text not null, "action_at" timestamptz not null, "comments" text null, "changes_requested" jsonb null, "delegated_from_id" text null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "approval_action_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_action_deleted_at" ON "approval_action" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_action_approval_request_id" ON "approval_action" ("approval_request_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_action_action_by_id" ON "approval_action" ("action_by_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_action_action_at" ON "approval_action" ("action_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "approval_request" ("id" text not null, "workflow_id" text not null, "company_id" text not null, "tenant_id" text null, "entity_type" text not null, "entity_id" text not null, "requested_by_id" text not null, "requested_at" timestamptz not null, "status" text check ("status" in ('pending', 'in_progress', 'approved', 'rejected', 'cancelled', 'expired')) not null default 'pending', "current_step" integer not null default 1, "request_data" jsonb null, "amount" numeric null, "currency_code" text null, "resolved_at" timestamptz null, "resolution_notes" text null, "metadata" jsonb null, "raw_amount" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "approval_request_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_request_deleted_at" ON "approval_request" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_request_workflow_id" ON "approval_request" ("workflow_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_request_company_id" ON "approval_request" ("company_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_request_entity_type_entity_id" ON "approval_request" ("entity_type", "entity_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_request_status" ON "approval_request" ("status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_request_requested_by_id" ON "approval_request" ("requested_by_id") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "approval_workflow" ("id" text not null, "company_id" text not null, "tenant_id" text null, "name" text not null, "description" text null, "workflow_type" text check ("workflow_type" in ('purchase_order', 'quote_request', 'quote_acceptance', 'user_registration', 'credit_increase', 'payment_terms_change', 'return_request', 'custom')) not null, "is_active" boolean not null default true, "priority" integer not null default 0, "conditions" jsonb null, "steps" jsonb not null, "notify_on_submit" boolean not null default true, "notify_on_approval" boolean not null default true, "notify_on_rejection" boolean not null default true, "notification_emails" jsonb null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "approval_workflow_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_workflow_deleted_at" ON "approval_workflow" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_workflow_company_id" ON "approval_workflow" ("company_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_workflow_tenant_id" ON "approval_workflow" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_workflow_workflow_type" ON "approval_workflow" ("workflow_type") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_approval_workflow_is_active_priority" ON "approval_workflow" ("is_active", "priority") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "company" ("id" text not null, "name" text not null, "legal_name" text null, "tax_id" text null, "email" text not null, "phone" text null, "industry" text null, "employee_count" integer null, "annual_revenue" numeric null, "credit_limit" numeric not null default '0', "credit_used" numeric not null default '0', "payment_terms_days" integer not null default 30, "status" text check ("status" in ('pending', 'active', 'suspended', 'inactive')) not null default 'pending', "tier" text check ("tier" in ('bronze', 'silver', 'gold', 'platinum')) not null default 'bronze', "approved_at" timestamptz null, "approved_by" text null, "rejection_reason" text null, "requires_approval" boolean not null default true, "auto_approve_limit" numeric null, "tenant_id" text not null, "store_id" text null, "billing_address" jsonb null, "shipping_addresses" jsonb null, "metadata" jsonb null, "raw_annual_revenue" jsonb null, "raw_credit_limit" jsonb not null default '{"value":"0","precision":20}', "raw_credit_used" jsonb not null default '{"value":"0","precision":20}', "raw_auto_approve_limit" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "company_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_company_deleted_at" ON "company" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "company_user" ("id" text not null, "company_id" text not null, "customer_id" text not null, "role" text check ("role" in ('admin', 'approver', 'buyer', 'viewer')) not null default 'buyer', "spending_limit" numeric null, "spending_limit_period" text check ("spending_limit_period" in ('daily', 'weekly', 'monthly', 'yearly')) null, "current_period_spend" numeric not null default '0', "period_start" timestamptz null, "approval_limit" numeric null, "status" text check ("status" in ('active', 'inactive')) not null default 'active', "invited_at" timestamptz null, "joined_at" timestamptz null, "metadata" jsonb null, "raw_spending_limit" jsonb null, "raw_current_period_spend" jsonb not null default '{"value":"0","precision":20}', "raw_approval_limit" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "company_user_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_company_user_deleted_at" ON "company_user" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "payment_terms" ("id" text not null, "tenant_id" text null, "name" text not null, "code" text not null, "description" text null, "terms_type" text check ("terms_type" in ('due_on_receipt', 'net_days', 'end_of_month', 'end_of_next_month', 'custom')) not null default 'net_days', "net_days" integer not null default 30, "early_payment_discount_percent" numeric null, "early_payment_discount_days" integer null, "late_fee_enabled" boolean not null default false, "late_fee_type" text check ("late_fee_type" in ('percentage', 'fixed')) null, "late_fee_amount" numeric null, "late_fee_grace_days" integer not null default 0, "is_default" boolean not null default false, "is_active" boolean not null default true, "min_order_value" numeric null, "company_tiers" jsonb null, "requires_credit_check" boolean not null default false, "min_credit_score" integer null, "metadata" jsonb null, "raw_early_payment_discount_percent" jsonb null, "raw_late_fee_amount" jsonb null, "raw_min_order_value" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "payment_terms_pkey" primary key ("id"));`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_payment_terms_code_unique" ON "payment_terms" ("code") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_payment_terms_deleted_at" ON "payment_terms" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_payment_terms_tenant_id" ON "payment_terms" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_payment_terms_is_active" ON "payment_terms" ("is_active") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_payment_terms_is_default" ON "payment_terms" ("is_default") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "purchase_order" ("id" text not null, "po_number" text not null, "company_id" text not null, "customer_id" text not null, "tenant_id" text null, "order_id" text null, "cart_id" text null, "quote_id" text null, "external_po_number" text null, "department" text null, "cost_center" text null, "project_code" text null, "status" text check ("status" in ('draft', 'pending_approval', 'approved', 'rejected', 'submitted', 'acknowledged', 'processing', 'partially_fulfilled', 'fulfilled', 'cancelled', 'closed')) not null default 'draft', "requires_approval" boolean not null default true, "approval_threshold" numeric null, "approved_by_id" text null, "approved_at" timestamptz null, "approval_notes" text null, "rejected_by_id" text null, "rejected_at" timestamptz null, "rejection_reason" text null, "currency_code" text not null default 'usd', "subtotal" numeric not null default 0, "discount_total" numeric not null default 0, "tax_total" numeric not null default 0, "shipping_total" numeric not null default 0, "total" numeric not null default 0, "payment_terms_id" text null, "payment_due_date" timestamptz null, "payment_status" text check ("payment_status" in ('not_due', 'due', 'overdue', 'partially_paid', 'paid')) not null default 'not_due', "issue_date" timestamptz null, "expected_delivery_date" timestamptz null, "actual_delivery_date" timestamptz null, "shipping_address" jsonb null, "billing_address" jsonb null, "shipping_method_id" text null, "internal_notes" text null, "vendor_notes" text null, "metadata" jsonb null, "raw_approval_threshold" jsonb null, "raw_subtotal" jsonb not null default '{"value":"0","precision":20}', "raw_discount_total" jsonb not null default '{"value":"0","precision":20}', "raw_tax_total" jsonb not null default '{"value":"0","precision":20}', "raw_shipping_total" jsonb not null default '{"value":"0","precision":20}', "raw_total" jsonb not null default '{"value":"0","precision":20}', "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "purchase_order_pkey" primary key ("id"));`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_purchase_order_po_number_unique" ON "purchase_order" ("po_number") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_deleted_at" ON "purchase_order" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_company_id" ON "purchase_order" ("company_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_customer_id" ON "purchase_order" ("customer_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_tenant_id_status" ON "purchase_order" ("tenant_id", "status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_status_payment_status" ON "purchase_order" ("status", "payment_status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_payment_due_date" ON "purchase_order" ("payment_due_date") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "purchase_order_item" ("id" text not null, "purchase_order_id" text not null, "product_id" text null, "variant_id" text null, "title" text not null, "description" text null, "sku" text null, "barcode" text null, "thumbnail" text null, "quantity" integer not null, "fulfilled_quantity" integer not null default 0, "unit_price" numeric not null, "original_price" numeric null, "discount_amount" numeric not null default 0, "tax_amount" numeric not null default 0, "subtotal" numeric not null, "total" numeric not null, "status" text check ("status" in ('pending', 'confirmed', 'partially_fulfilled', 'fulfilled', 'cancelled', 'backordered')) not null default 'pending', "expected_ship_date" timestamptz null, "actual_ship_date" timestamptz null, "tracking_number" text null, "notes" text null, "metadata" jsonb null, "raw_unit_price" jsonb not null, "raw_original_price" jsonb null, "raw_discount_amount" jsonb not null default '{"value":"0","precision":20}', "raw_tax_amount" jsonb not null default '{"value":"0","precision":20}', "raw_subtotal" jsonb not null, "raw_total" jsonb not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "purchase_order_item_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_item_deleted_at" ON "purchase_order_item" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_item_purchase_order_id" ON "purchase_order_item" ("purchase_order_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_item_product_id" ON "purchase_order_item" ("product_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_purchase_order_item_variant_id" ON "purchase_order_item" ("variant_id") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "tax_exemption" ("id" text not null, "company_id" text not null, "tenant_id" text null, "certificate_number" text not null, "certificate_type" text check ("certificate_type" in ('resale', 'nonprofit', 'government', 'manufacturer', 'agricultural', 'educational', 'medical', 'religious', 'other')) not null, "issuing_state" text null, "issuing_country" text null, "issuing_authority" text null, "issue_date" timestamptz not null, "expiration_date" timestamptz null, "is_permanent" boolean not null default false, "status" text check ("status" in ('pending_verification', 'verified', 'rejected', 'expired', 'revoked')) not null default 'pending_verification', "verified_by_id" text null, "verified_at" timestamptz null, "verification_notes" text null, "rejection_reason" text null, "exemption_percentage" numeric not null default 100, "applicable_categories" jsonb null, "applicable_regions" jsonb null, "certificate_file_url" text null, "supporting_documents" jsonb null, "last_used_at" timestamptz null, "usage_count" integer not null default 0, "metadata" jsonb null, "raw_exemption_percentage" jsonb not null default '{"value":"100","precision":20}', "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tax_exemption_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tax_exemption_deleted_at" ON "tax_exemption" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tax_exemption_company_id" ON "tax_exemption" ("company_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tax_exemption_tenant_id" ON "tax_exemption" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tax_exemption_status" ON "tax_exemption" ("status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tax_exemption_expiration_date" ON "tax_exemption" ("expiration_date") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tax_exemption_certificate_number" ON "tax_exemption" ("certificate_number") WHERE deleted_at IS NULL;`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "approval_action" cascade;`);

    this.addSql(`drop table if exists "approval_request" cascade;`);

    this.addSql(`drop table if exists "approval_workflow" cascade;`);

    this.addSql(`drop table if exists "company" cascade;`);

    this.addSql(`drop table if exists "company_user" cascade;`);

    this.addSql(`drop table if exists "payment_terms" cascade;`);

    this.addSql(`drop table if exists "purchase_order" cascade;`);

    this.addSql(`drop table if exists "purchase_order_item" cascade;`);

    this.addSql(`drop table if exists "tax_exemption" cascade;`);
  }

}
