import { Migration } from "@medusajs/framework/mikro-orm/migrations";

export class Migration20260208081244 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table if exists "tenant_user" drop constraint if exists "tenant_user_tenant_id_user_id_unique";`);
    this.addSql(`alter table if exists "tenant_settings" drop constraint if exists "tenant_settings_tenant_id_unique";`);
    this.addSql(`alter table if exists "tenant_invoice" drop constraint if exists "tenant_invoice_invoice_number_unique";`);
    this.addSql(`alter table if exists "tenant" drop constraint if exists "tenant_handle_unique";`);
    this.addSql(`alter table if exists "tenant" drop constraint if exists "tenant_slug_unique";`);
    this.addSql(`create table if not exists "tenant" ("id" text not null, "name" text not null, "slug" text not null, "handle" text not null, "domain" text null, "custom_domains" jsonb null, "residency_zone" text check ("residency_zone" in ('GCC', 'EU', 'MENA', 'APAC', 'AMERICAS', 'GLOBAL')) not null default 'GLOBAL', "country_id" text null, "governance_authority_id" text null, "default_locale" text not null default 'en', "supported_locales" jsonb not null default '["en"]', "timezone" text not null default 'UTC', "default_currency" text not null default 'usd', "date_format" text not null default 'dd/MM/yyyy', "default_persona_id" text null, "logo_url" text null, "favicon_url" text null, "primary_color" text null, "accent_color" text null, "font_family" text null, "branding" jsonb null, "status" text check ("status" in ('active', 'suspended', 'trial', 'archived', 'inactive')) not null default 'trial', "subscription_tier" text check ("subscription_tier" in ('basic', 'pro', 'enterprise', 'custom')) not null default 'basic', "billing_email" text null, "billing_address" jsonb null, "trial_starts_at" timestamptz null, "trial_ends_at" timestamptz null, "settings" jsonb null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tenant_pkey" primary key ("id"));`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_tenant_slug_unique" ON "tenant" ("slug") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_tenant_handle_unique" ON "tenant" ("handle") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_deleted_at" ON "tenant" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "tenant_billing" ("id" text not null, "tenant_id" text not null, "subscription_status" text check ("subscription_status" in ('trialing', 'active', 'past_due', 'canceled', 'unpaid')) not null default 'trialing', "plan_id" text null, "plan_name" text null, "plan_type" text check ("plan_type" in ('monthly', 'yearly')) not null default 'monthly', "base_price" numeric not null default 0, "currency_code" text not null default 'usd', "usage_metering_enabled" boolean not null default false, "usage_price_per_unit" numeric null, "usage_unit_name" text null, "included_units" integer not null default 0, "current_period_start" timestamptz null, "current_period_end" timestamptz null, "current_usage" integer not null default 0, "current_usage_cost" numeric not null default 0, "payment_method_id" text null, "stripe_customer_id" text null, "stripe_subscription_id" text null, "last_invoice_date" timestamptz null, "last_invoice_amount" numeric null, "next_invoice_date" timestamptz null, "max_products" integer null, "max_orders_per_month" integer null, "max_storage_gb" integer null, "max_team_members" integer null, "metadata" jsonb null, "raw_base_price" jsonb not null default '{"value":"0","precision":20}', "raw_usage_price_per_unit" jsonb null, "raw_current_usage_cost" jsonb not null default '{"value":"0","precision":20}', "raw_last_invoice_amount" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tenant_billing_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_billing_deleted_at" ON "tenant_billing" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_billing_tenant_id" ON "tenant_billing" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_billing_subscription_status" ON "tenant_billing" ("subscription_status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_billing_stripe_customer_id" ON "tenant_billing" ("stripe_customer_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_billing_next_invoice_date" ON "tenant_billing" ("next_invoice_date") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "tenant_invoice" ("id" text not null, "tenant_id" text not null, "billing_id" text not null, "invoice_number" text not null, "period_start" timestamptz not null, "period_end" timestamptz not null, "currency_code" text not null default 'usd', "base_amount" numeric not null default 0, "usage_amount" numeric not null default 0, "discount_amount" numeric not null default 0, "tax_amount" numeric not null default 0, "total_amount" numeric not null default 0, "status" text check ("status" in ('draft', 'open', 'paid', 'void', 'uncollectible')) not null default 'draft', "paid_at" timestamptz null, "payment_method" text null, "stripe_invoice_id" text null, "invoice_pdf_url" text null, "due_date" timestamptz null, "line_items" jsonb null, "metadata" jsonb null, "raw_base_amount" jsonb not null default '{"value":"0","precision":20}', "raw_usage_amount" jsonb not null default '{"value":"0","precision":20}', "raw_discount_amount" jsonb not null default '{"value":"0","precision":20}', "raw_tax_amount" jsonb not null default '{"value":"0","precision":20}', "raw_total_amount" jsonb not null default '{"value":"0","precision":20}', "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tenant_invoice_pkey" primary key ("id"));`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_tenant_invoice_invoice_number_unique" ON "tenant_invoice" ("invoice_number") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_invoice_deleted_at" ON "tenant_invoice" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_invoice_tenant_id" ON "tenant_invoice" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_invoice_billing_id" ON "tenant_invoice" ("billing_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_invoice_status" ON "tenant_invoice" ("status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_invoice_due_date" ON "tenant_invoice" ("due_date") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "tenant_settings" ("id" text not null, "tenant_id" text not null, "timezone" text not null default 'UTC', "date_format" text not null default 'YYYY-MM-DD', "time_format" text not null default 'HH:mm', "default_locale" text not null default 'en', "supported_locales" jsonb null, "default_currency" text not null default 'usd', "supported_currencies" jsonb null, "primary_color" text null, "secondary_color" text null, "accent_color" text null, "font_family" text null, "custom_css" text null, "email_from_name" text null, "email_from_address" text null, "email_reply_to" text null, "smtp_host" text null, "smtp_port" integer null, "smtp_user" text null, "smtp_password" text null, "guest_checkout_enabled" boolean not null default true, "require_phone" boolean not null default false, "require_company" boolean not null default false, "min_order_value" numeric null, "max_order_value" numeric null, "track_inventory" boolean not null default true, "allow_backorders" boolean not null default false, "low_stock_threshold" integer not null default 10, "order_number_prefix" text null, "order_number_start" integer not null default 1000, "auto_archive_days" integer not null default 90, "accepted_payment_methods" jsonb null, "payment_capture_method" text check ("payment_capture_method" in ('automatic', 'manual')) not null default 'automatic', "free_shipping_threshold" numeric null, "default_weight_unit" text check ("default_weight_unit" in ('kg', 'lb', 'oz', 'g')) not null default 'kg', "default_dimension_unit" text check ("default_dimension_unit" in ('cm', 'in', 'm', 'ft')) not null default 'cm', "tax_inclusive_pricing" boolean not null default false, "tax_provider" text null, "notify_on_new_order" boolean not null default true, "notify_on_low_stock" boolean not null default true, "notification_emails" jsonb null, "google_analytics_id" text null, "facebook_pixel_id" text null, "google_tag_manager_id" text null, "api_rate_limit" integer not null default 1000, "webhook_secret" text null, "metadata" jsonb null, "raw_min_order_value" jsonb null, "raw_max_order_value" jsonb null, "raw_free_shipping_threshold" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tenant_settings_pkey" primary key ("id"));`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_tenant_settings_tenant_id_unique" ON "tenant_settings" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_settings_deleted_at" ON "tenant_settings" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_settings_tenant_id" ON "tenant_settings" ("tenant_id") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "tenant_usage_record" ("id" text not null, "tenant_id" text not null, "billing_id" text not null, "usage_type" text check ("usage_type" in ('orders', 'products', 'storage', 'api_calls', 'bandwidth', 'custom')) not null, "quantity" integer not null, "unit_price" numeric null, "total_cost" numeric null, "recorded_at" timestamptz not null, "period_start" timestamptz not null, "period_end" timestamptz not null, "reference_type" text null, "reference_id" text null, "metadata" jsonb null, "raw_unit_price" jsonb null, "raw_total_cost" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tenant_usage_record_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_usage_record_deleted_at" ON "tenant_usage_record" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_usage_record_tenant_id" ON "tenant_usage_record" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_usage_record_billing_id" ON "tenant_usage_record" ("billing_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_usage_record_usage_type_period_start" ON "tenant_usage_record" ("usage_type", "period_start") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_usage_record_recorded_at" ON "tenant_usage_record" ("recorded_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "tenant_user" ("id" text not null, "tenant_id" text not null, "user_id" text not null, "role" text check ("role" in ('super-admin', 'tenant-admin', 'compliance-officer', 'auditor', 'city-manager', 'district-manager', 'zone-operator', 'facility-operator', 'asset-technician', 'viewer')) not null default 'viewer', "role_level" integer not null default 10, "assigned_nodes" jsonb null, "assigned_node_ids" jsonb null, "permissions" jsonb null, "status" text check ("status" in ('active', 'inactive', 'invited')) not null default 'invited', "invitation_token" text null, "invitation_sent_at" timestamptz null, "invitation_accepted_at" timestamptz null, "invited_by_id" text null, "last_active_at" timestamptz null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "tenant_user_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_user_deleted_at" ON "tenant_user" ("deleted_at") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_user_tenant_id" ON "tenant_user" ("tenant_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_user_user_id" ON "tenant_user" ("user_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_tenant_user_tenant_id_user_id_unique" ON "tenant_user" ("tenant_id", "user_id") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_user_status" ON "tenant_user" ("status") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_user_invitation_token" ON "tenant_user" ("invitation_token") WHERE deleted_at IS NULL;`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_tenant_user_role_level" ON "tenant_user" ("role_level") WHERE deleted_at IS NULL;`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "tenant" cascade;`);

    this.addSql(`drop table if exists "tenant_billing" cascade;`);

    this.addSql(`drop table if exists "tenant_invoice" cascade;`);

    this.addSql(`drop table if exists "tenant_settings" cascade;`);

    this.addSql(`drop table if exists "tenant_usage_record" cascade;`);

    this.addSql(`drop table if exists "tenant_user" cascade;`);
  }

}
