// @ts-nocheck
import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys, Modules } from "@medusajs/framework/utils"
import { createProductsWorkflow } from "@medusajs/medusa/core-flows"
import { SeedContext, getImage, getThumb, sarPrice } from "./seed-utils.js"

export default async function seedCatalog({ container }: ExecArgs, ctx: SeedContext): Promise<void> {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)

  logger.info("========================================")
  logger.info("Seeding Product Catalog (48 products)")
  logger.info("========================================\n")

  const sc = [{ id: ctx.salesChannelIds[0] }]
  const rid = ctx.regionId
  const cat = (handle: string) => ctx.categoryIds[handle]
  const price = (amount: number) => [{ amount: sarPrice(amount), currency_code: "sar", region_id: rid }]

  const batch1 = [
    {
      title: "Samsung Galaxy S24 Ultra",
      handle: "samsung-galaxy-s24-ultra",
      description: "Latest Samsung flagship smartphone with S Pen, 200MP camera, and Titanium frame. Available in Saudi Arabia.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("electronics", 0),
      images: [{ url: getImage("electronics", 0) }],
      categories: [{ id: cat("electronics") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-ELC-001",
        manage_inventory: true,
        prices: price(4999),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "MacBook Pro 16\" M3",
      handle: "macbook-pro-16-m3",
      description: "Apple MacBook Pro with M3 chip, 16-inch Liquid Retina XDR display, and up to 22 hours of battery life.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("electronics", 1),
      images: [{ url: getImage("electronics", 1) }],
      categories: [{ id: cat("electronics") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-ELC-002",
        manage_inventory: true,
        prices: price(12499),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Sony WH-1000XM5 Headphones",
      handle: "sony-wh-1000xm5-headphones",
      description: "Industry-leading noise cancelling headphones with exceptional sound quality and 30-hour battery life.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("electronics", 2),
      images: [{ url: getImage("electronics", 2) }],
      categories: [{ id: cat("electronics") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-ELC-003",
        manage_inventory: true,
        prices: price(1499),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Apple Watch Series 9",
      handle: "apple-watch-series-9",
      description: "Advanced health and fitness smartwatch with blood oxygen monitoring, ECG, and always-on Retina display.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("electronics", 3),
      images: [{ url: getImage("electronics", 3) }],
      categories: [{ id: cat("electronics") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-ELC-004",
        manage_inventory: true,
        prices: price(1799),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Premium Saudi Thobe (White)",
      handle: "premium-saudi-thobe-white",
      description: "Elegant white Saudi thobe crafted from premium cotton fabric with traditional embroidery. Perfect for daily wear and special occasions.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fashion", 0),
      images: [{ url: getImage("fashion", 0) }],
      categories: [{ id: cat("fashion") }],
      sales_channels: sc,
      options: [{ title: "Size", values: ["S", "M", "L", "XL"] }],
      variants: [
        { title: "Small", sku: "DAK-FSH-001-S", manage_inventory: true, prices: price(599), options: { Size: "S" } },
        { title: "Medium", sku: "DAK-FSH-001-M", manage_inventory: true, prices: price(599), options: { Size: "M" } },
        { title: "Large", sku: "DAK-FSH-001-L", manage_inventory: true, prices: price(599), options: { Size: "L" } },
        { title: "X-Large", sku: "DAK-FSH-001-XL", manage_inventory: true, prices: price(599), options: { Size: "XL" } },
      ],
    },
    {
      title: "Leather Business Shoes",
      handle: "leather-business-shoes",
      description: "Premium Italian leather business shoes with cushioned insole. Ideal for the modern Saudi professional.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fashion", 1),
      images: [{ url: getImage("fashion", 1) }],
      categories: [{ id: cat("fashion") }],
      sales_channels: sc,
      options: [{ title: "Size", values: ["40", "41", "42", "43", "44"] }],
      variants: [
        { title: "Size 40", sku: "DAK-FSH-002-40", manage_inventory: true, prices: price(849), options: { Size: "40" } },
        { title: "Size 41", sku: "DAK-FSH-002-41", manage_inventory: true, prices: price(849), options: { Size: "41" } },
        { title: "Size 42", sku: "DAK-FSH-002-42", manage_inventory: true, prices: price(849), options: { Size: "42" } },
        { title: "Size 43", sku: "DAK-FSH-002-43", manage_inventory: true, prices: price(849), options: { Size: "43" } },
        { title: "Size 44", sku: "DAK-FSH-002-44", manage_inventory: true, prices: price(849), options: { Size: "44" } },
      ],
    },
    {
      title: "Designer Abaya Collection",
      handle: "designer-abaya-collection-catalog",
      description: "Contemporary designer abaya with intricate beadwork and flowing crepe fabric. A blend of tradition and modern fashion.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fashion", 2),
      images: [{ url: getImage("fashion", 2) }],
      categories: [{ id: cat("fashion") }],
      sales_channels: sc,
      options: [{ title: "Size", values: ["S", "M", "L"] }],
      variants: [
        { title: "Small", sku: "DAK-FSH-003-S", manage_inventory: true, prices: price(1299), options: { Size: "S" } },
        { title: "Medium", sku: "DAK-FSH-003-M", manage_inventory: true, prices: price(1299), options: { Size: "M" } },
        { title: "Large", sku: "DAK-FSH-003-L", manage_inventory: true, prices: price(1299), options: { Size: "L" } },
      ],
    },
    {
      title: "Luxury Watch Collection",
      handle: "luxury-watch-collection",
      description: "Exquisite luxury timepiece with Swiss movement, sapphire crystal, and genuine leather strap. A statement of elegance.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fashion", 3),
      images: [{ url: getImage("fashion", 3) }],
      categories: [{ id: cat("fashion") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-FSH-004",
        manage_inventory: true,
        prices: price(3499),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Premium Saudi Dates Gift Box (1kg)",
      handle: "premium-saudi-dates-gift-box",
      description: "Hand-selected premium Ajwa and Sukkari dates from Al-Madinah, beautifully packaged in an elegant gift box.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("food", 0),
      images: [{ url: getImage("food", 0) }],
      categories: [{ id: cat("food-beverages") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-FNB-001",
        manage_inventory: true,
        prices: price(189),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Arabic Coffee Collection Set",
      handle: "arabic-coffee-collection-set",
      description: "Premium Saudi Arabic coffee with cardamom and saffron. Includes traditional Dallah pot and six finjan cups.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("food", 1),
      images: [{ url: getImage("food", 1) }],
      categories: [{ id: cat("food-beverages") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-FNB-002",
        manage_inventory: true,
        prices: price(149),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Saudi Spice Mix Set (6 Pack)",
      handle: "saudi-spice-mix-set",
      description: "Authentic Saudi spice collection featuring Kabsa, Mandi, and Saleeg blends. Essential for traditional Saudi cooking.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("food", 2),
      images: [{ url: getImage("food", 2) }],
      categories: [{ id: cat("food-beverages") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-FNB-003",
        manage_inventory: true,
        prices: price(89),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Organic Honey (Saudi)",
      handle: "organic-honey-saudi",
      description: "Pure organic Sidr honey sourced from the mountains of Saudi Arabia. Known for its exceptional flavor and health benefits.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("food", 3),
      images: [{ url: getImage("food", 3) }],
      categories: [{ id: cat("food-beverages") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-FNB-004",
        manage_inventory: true,
        prices: price(249),
        options: { Default: "Standard" },
      }],
    },
  ]

  const batch2 = [
    {
      title: "Majlis Sofa Set",
      handle: "majlis-sofa-set",
      description: "Traditional Arabian majlis seating set with premium brocade upholstery and geometric patterns. Seats up to 10 guests.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("home", 0),
      images: [{ url: getImage("home", 0) }],
      categories: [{ id: cat("home-living") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HML-001",
        manage_inventory: true,
        prices: price(8999),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Arabic Coffee Table Set",
      handle: "arabic-coffee-table-set",
      description: "Handcrafted Arabic coffee table with intricate woodwork and mother-of-pearl inlay. A centerpiece for any majlis.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("home", 1),
      images: [{ url: getImage("home", 1) }],
      categories: [{ id: cat("home-living") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HML-002",
        manage_inventory: true,
        prices: price(2499),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Smart LED Chandelier",
      handle: "smart-led-chandelier",
      description: "Modern smart LED chandelier with app control, dimmable lighting, and color temperature adjustment. Energy efficient design.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("home", 2),
      images: [{ url: getImage("home", 2) }],
      categories: [{ id: cat("home-living") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HML-003",
        manage_inventory: true,
        prices: price(1899),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Premium Kitchen Appliance Set",
      handle: "premium-kitchen-appliance-set",
      description: "Complete kitchen set including stand mixer, food processor, and blender. Premium stainless steel construction.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("home", 3),
      images: [{ url: getImage("home", 3) }],
      categories: [{ id: cat("home-living") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HML-004",
        manage_inventory: true,
        prices: price(3299),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Oud Perfume Collection",
      handle: "oud-perfume-collection",
      description: "Luxurious oud-based perfume collection featuring three signature scents. Crafted from aged Cambodian oud and Arabian rose.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("beauty", 0),
      images: [{ url: getImage("beauty", 0) }],
      categories: [{ id: cat("beauty") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BTY-001",
        manage_inventory: true,
        prices: price(899),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Natural Skincare Set",
      handle: "natural-skincare-set",
      description: "All-natural skincare bundle with Dead Sea minerals, argan oil cleanser, and camel milk moisturizer. For all skin types.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("beauty", 1),
      images: [{ url: getImage("beauty", 1) }],
      categories: [{ id: cat("beauty") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BTY-002",
        manage_inventory: true,
        prices: price(449),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Hair Care Essentials Kit",
      handle: "hair-care-essentials-kit",
      description: "Professional hair care kit with Moroccan argan shampoo, conditioner, and hair serum. Nourishes and strengthens hair.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("beauty", 2),
      images: [{ url: getImage("beauty", 2) }],
      categories: [{ id: cat("beauty") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BTY-003",
        manage_inventory: true,
        prices: price(299),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Luxury Makeup Palette",
      handle: "luxury-makeup-palette",
      description: "Premium 24-shade eyeshadow palette with desert-inspired colors. Long-lasting, highly pigmented formula.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("beauty", 3),
      images: [{ url: getImage("beauty", 3) }],
      categories: [{ id: cat("beauty") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BTY-004",
        manage_inventory: true,
        prices: price(349),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Premium Vitamin Pack",
      handle: "premium-vitamin-pack",
      description: "Comprehensive daily vitamin pack with Vitamin D, Omega-3, and multivitamins. Formulated for the Saudi climate.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("healthcare", 0),
      images: [{ url: getImage("healthcare", 0) }],
      categories: [{ id: cat("health") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HLT-001",
        manage_inventory: true,
        prices: price(199),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Blood Pressure Monitor",
      handle: "blood-pressure-monitor",
      description: "Digital blood pressure monitor with large LCD display, irregular heartbeat detection, and memory for 120 readings.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("healthcare", 1),
      images: [{ url: getImage("healthcare", 1) }],
      categories: [{ id: cat("health") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HLT-002",
        manage_inventory: true,
        prices: price(349),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Fitness Tracker Band",
      handle: "fitness-tracker-band",
      description: "Waterproof fitness tracker with heart rate monitor, sleep tracking, and 14-day battery life. Arabic language support.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("healthcare", 2),
      images: [{ url: getImage("healthcare", 2) }],
      categories: [{ id: cat("health") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HLT-003",
        manage_inventory: true,
        prices: price(249),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "First Aid Premium Kit",
      handle: "first-aid-premium-kit",
      description: "Comprehensive first aid kit with 200+ medical supplies. Ideal for home, car, and outdoor use in Saudi Arabia.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("healthcare", 3),
      images: [{ url: getImage("healthcare", 3) }],
      categories: [{ id: cat("health") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-HLT-004",
        manage_inventory: true,
        prices: price(179),
        options: { Default: "Standard" },
      }],
    },
  ]

  const batch3 = [
    {
      title: "Car Care Premium Kit",
      handle: "car-care-premium-kit",
      description: "Complete car detailing kit with premium wax, interior cleaner, and microfiber cloths. Protects against desert sand and heat.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("automotive", 0),
      images: [{ url: getImage("automotive", 0) }],
      categories: [{ id: cat("automotive") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-AUT-001",
        manage_inventory: true,
        prices: price(299),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Dash Camera HD Pro",
      handle: "dash-camera-hd-pro",
      description: "Full HD dash camera with night vision, GPS tracking, and heat-resistant design built for Saudi summers.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("automotive", 1),
      images: [{ url: getImage("automotive", 1) }],
      categories: [{ id: cat("automotive") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-AUT-002",
        manage_inventory: true,
        prices: price(599),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Leather Car Seat Covers",
      handle: "leather-car-seat-covers",
      description: "Premium leather car seat covers with cooling gel technology. Universal fit for sedans and SUVs popular in Saudi Arabia.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("automotive", 2),
      images: [{ url: getImage("automotive", 2) }],
      categories: [{ id: cat("automotive") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-AUT-003",
        manage_inventory: true,
        prices: price(1499),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Car Air Purifier",
      handle: "car-air-purifier",
      description: "HEPA car air purifier with activated carbon filter. Removes dust, allergens, and odors. Compact USB-powered design.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("automotive", 3),
      images: [{ url: getImage("automotive", 3) }],
      categories: [{ id: cat("automotive") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-AUT-004",
        manage_inventory: true,
        prices: price(399),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Home Gym Set Complete",
      handle: "home-gym-set-complete",
      description: "Complete home gym package with adjustable dumbbells, bench, resistance bands, and yoga mat. Everything for a full workout.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fitness", 0),
      images: [{ url: getImage("fitness", 0) }],
      categories: [{ id: cat("sports") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-SPT-001",
        manage_inventory: true,
        prices: price(4999),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Yoga Mat Premium",
      handle: "yoga-mat-premium",
      description: "Extra-thick non-slip yoga mat with alignment markings. Made from eco-friendly TPE material. Includes carry strap.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fitness", 1),
      images: [{ url: getImage("fitness", 1) }],
      categories: [{ id: cat("sports") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-SPT-002",
        manage_inventory: true,
        prices: price(199),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Running Shoes Pro",
      handle: "running-shoes-pro",
      description: "Lightweight running shoes with breathable mesh upper and responsive cushioning. Designed for hot climate training.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fitness", 2),
      images: [{ url: getImage("fitness", 2) }],
      categories: [{ id: cat("sports") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-SPT-003",
        manage_inventory: true,
        prices: price(699),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Protein Supplement Pack",
      handle: "protein-supplement-pack",
      description: "Premium whey protein isolate pack with three flavors. Halal certified, low sugar, and high protein per serving.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("fitness", 3),
      images: [{ url: getImage("fitness", 3) }],
      categories: [{ id: cat("sports") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-SPT-004",
        manage_inventory: true,
        prices: price(249),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Arabic Literature Collection",
      handle: "arabic-literature-collection",
      description: "Curated collection of classic Arabic literature including works by Naguib Mahfouz and Taha Hussein. Hardcover editions.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("education", 0),
      images: [{ url: getImage("education", 0) }],
      categories: [{ id: cat("books") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BKS-001",
        manage_inventory: true,
        prices: price(149),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Business Strategy Bundle",
      handle: "business-strategy-bundle",
      description: "Essential business strategy books including Vision 2030 guides and entrepreneurship handbooks for the Saudi market.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("education", 1),
      images: [{ url: getImage("education", 1) }],
      categories: [{ id: cat("books") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BKS-002",
        manage_inventory: true,
        prices: price(199),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Children's Learning Set",
      handle: "childrens-learning-set",
      description: "Interactive Arabic and English learning set for children ages 3-8. Includes activity books, flashcards, and stickers.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("education", 2),
      images: [{ url: getImage("education", 2) }],
      categories: [{ id: cat("books") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BKS-003",
        manage_inventory: true,
        prices: price(129),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Islamic Studies Collection",
      handle: "islamic-studies-collection",
      description: "Comprehensive Islamic studies collection with Quran tafsir, hadith compilations, and fiqh reference books.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("education", 3),
      images: [{ url: getImage("education", 3) }],
      categories: [{ id: cat("books") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BKS-004",
        manage_inventory: true,
        prices: price(179),
        options: { Default: "Standard" },
      }],
    },
  ]

  const batch4 = [
    {
      title: "Baby Essential Starter Kit",
      handle: "baby-essential-starter-kit",
      description: "Complete baby starter kit with organic cotton onesies, bottles, pacifiers, and grooming essentials. Perfect for new parents.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("pets", 0),
      images: [{ url: getImage("pets", 0) }],
      categories: [{ id: cat("baby-kids") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BBY-001",
        manage_inventory: true,
        prices: price(599),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Children's Educational Toys",
      handle: "childrens-educational-toys",
      description: "STEM educational toy set with building blocks, science experiments, and Arabic alphabet puzzles for ages 4-10.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("pets", 1),
      images: [{ url: getImage("pets", 1) }],
      categories: [{ id: cat("baby-kids") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BBY-002",
        manage_inventory: true,
        prices: price(249),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Kids Fashion Pack",
      handle: "kids-fashion-pack",
      description: "Adorable kids clothing pack with seasonal outfits. Comfortable, durable fabrics suitable for the Saudi climate.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("pets", 2),
      images: [{ url: getImage("pets", 2) }],
      categories: [{ id: cat("baby-kids") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BBY-003",
        manage_inventory: true,
        prices: price(399),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Baby Organic Care Set",
      handle: "baby-organic-care-set",
      description: "Gentle organic baby care set with shampoo, lotion, and diaper cream. Dermatologist tested and hypoallergenic.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("pets", 3),
      images: [{ url: getImage("pets", 3) }],
      categories: [{ id: cat("baby-kids") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-BBY-004",
        manage_inventory: true,
        prices: price(299),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Fresh Fruit Box (Weekly)",
      handle: "fresh-fruit-box-weekly",
      description: "Weekly delivery of fresh seasonal fruits sourced from local Saudi farms. Includes mangoes, dates, and citrus fruits.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("grocery", 0),
      images: [{ url: getImage("grocery", 0) }],
      categories: [{ id: cat("grocery") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-GRC-001",
        manage_inventory: true,
        prices: price(99),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Premium Meat Pack",
      handle: "premium-meat-pack",
      description: "Premium halal meat pack with lamb chops, beef tenderloin, and chicken breast. Sourced from certified Saudi farms.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("grocery", 1),
      images: [{ url: getImage("grocery", 1) }],
      categories: [{ id: cat("grocery") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-GRC-002",
        manage_inventory: true,
        prices: price(249),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Pantry Essentials Bundle",
      handle: "pantry-essentials-bundle",
      description: "Complete pantry bundle with rice, flour, cooking oil, spices, and canned goods. Stock up for the month.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("grocery", 2),
      images: [{ url: getImage("grocery", 2) }],
      categories: [{ id: cat("grocery") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-GRC-003",
        manage_inventory: true,
        prices: price(179),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Organic Dairy Pack",
      handle: "organic-dairy-pack",
      description: "Fresh organic dairy pack with milk, yogurt, cheese, and laban. From certified organic Saudi dairy farms.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("grocery", 3),
      images: [{ url: getImage("grocery", 3) }],
      categories: [{ id: cat("grocery") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-GRC-004",
        manage_inventory: true,
        prices: price(89),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Arabic Language Course",
      handle: "arabic-language-course",
      description: "Comprehensive online Arabic language course with video lessons, interactive exercises, and live tutoring sessions.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("digital", 0),
      images: [{ url: getImage("digital", 0) }],
      categories: [{ id: cat("digital") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-DIG-001",
        manage_inventory: true,
        prices: price(499),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Photography Masterclass",
      handle: "photography-masterclass",
      description: "Professional photography masterclass covering desert landscapes, architecture, and portrait photography techniques.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("digital", 1),
      images: [{ url: getImage("digital", 1) }],
      categories: [{ id: cat("digital") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-DIG-002",
        manage_inventory: true,
        prices: price(299),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Business Analytics Course",
      handle: "business-analytics-course",
      description: "Data-driven business analytics course aligned with Saudi Vision 2030. Covers Excel, Python, and Power BI.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("digital", 2),
      images: [{ url: getImage("digital", 2) }],
      categories: [{ id: cat("digital") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-DIG-003",
        manage_inventory: true,
        prices: price(699),
        options: { Default: "Standard" },
      }],
    },
    {
      title: "Kids Coding Camp Access",
      handle: "kids-coding-camp-access",
      description: "Interactive coding camp for kids ages 8-14. Learn Scratch, Python, and web development with Arabic instruction.",
      status: "published",
      is_giftcard: false,
      thumbnail: getThumb("digital", 3),
      images: [{ url: getImage("digital", 3) }],
      categories: [{ id: cat("digital") }],
      sales_channels: sc,
      options: [{ title: "Default", values: ["Standard"] }],
      variants: [{
        title: "Default",
        sku: "DAK-DIG-004",
        manage_inventory: true,
        prices: price(399),
        options: { Default: "Standard" },
      }],
    },
  ]

  const batches = [
    { name: "Batch 1 (Electronics, Fashion, Food)", products: batch1 },
    { name: "Batch 2 (Home, Beauty, Health, Books)", products: batch2 },
    { name: "Batch 3 (Automotive, Sports, Books cont.)", products: batch3 },
    { name: "Batch 4 (Baby, Grocery, Digital)", products: batch4 },
  ]

  const allProductIds: string[] = []

  for (const batch of batches) {
    try {
      logger.info(`  Creating ${batch.name} (${batch.products.length} products)...`)
      const { result } = await createProductsWorkflow(container).run({
        input: { products: batch.products },
      })
      const ids = result.map((p: any) => p.id)
      allProductIds.push(...ids)
      logger.info(`  ✓ ${batch.name} created (${ids.length} products)`)
    } catch (error: any) {
      logger.error(`  ✗ ${batch.name} failed: ${error.message}`)
    }
  }

  ctx.productIds = allProductIds

  logger.info(`\n========================================`)
  logger.info(`Product Catalog Seeding Complete`)
  logger.info(`Total products created: ${allProductIds.length}`)
  logger.info(`========================================\n`)
}
