import type { FormField } from "./ui/form-drawer"

export interface CrudConfig {
  moduleKey: string
  apiEndpoint: string
  dataKey: string
  singularKey: string
  label: string
  singularLabel: string
  fields: FormField[]
  defaultValues: Record<string, any>
  canCreate?: boolean
  canEdit?: boolean
  canDelete?: boolean
}

export const crudConfigs: Record<string, CrudConfig> = {
  products: {
    moduleKey: "products",
    apiEndpoint: "/admin/products",
    dataKey: "products",
    singularKey: "product",
    label: "Products",
    singularLabel: "Product",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Product title" },
      { key: "subtitle", label: "Subtitle", type: "text", placeholder: "Product subtitle" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Product description" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "published", label: "Published" },
        { value: "archived", label: "Archived" },
      ]},
      { key: "handle", label: "Handle", type: "text", placeholder: "product-handle" },
      { key: "thumbnail", label: "Thumbnail URL", type: "url", placeholder: "https://example.com/image.jpg" },
    ],
    defaultValues: { title: "", subtitle: "", description: "", status: "draft", handle: "", thumbnail: "" },
  },

  orders: {
    moduleKey: "orders",
    apiEndpoint: "/admin/orders",
    dataKey: "orders",
    singularKey: "order",
    label: "Orders",
    singularLabel: "Order",
    canCreate: false,
    canDelete: false,
    fields: [
      { key: "status", label: "Status", type: "select", options: [
        { value: "pending", label: "Pending" },
        { value: "processing", label: "Processing" },
        { value: "shipped", label: "Shipped" },
        { value: "delivered", label: "Delivered" },
        { value: "cancelled", label: "Cancelled" },
      ]},
      { key: "fulfillment_status", label: "Fulfillment Status", type: "select", options: [
        { value: "not_fulfilled", label: "Not Fulfilled" },
        { value: "partially_fulfilled", label: "Partially Fulfilled" },
        { value: "fulfilled", label: "Fulfilled" },
        { value: "returned", label: "Returned" },
      ]},
      { key: "notes", label: "Notes", type: "textarea", placeholder: "Order notes" },
    ],
    defaultValues: { status: "pending", fulfillment_status: "not_fulfilled", notes: "" },
  },

  customers: {
    moduleKey: "customers",
    apiEndpoint: "/admin/customers",
    dataKey: "customers",
    singularKey: "customer",
    label: "Customers",
    singularLabel: "Customer",
    fields: [
      { key: "first_name", label: "First Name", type: "text", required: true, placeholder: "First name" },
      { key: "last_name", label: "Last Name", type: "text", required: true, placeholder: "Last name" },
      { key: "email", label: "Email", type: "email", required: true, placeholder: "email@example.com" },
      { key: "phone", label: "Phone", type: "text", placeholder: "+1 (555) 000-0000" },
    ],
    defaultValues: { first_name: "", last_name: "", email: "", phone: "" },
  },

  vendors: {
    moduleKey: "vendors",
    apiEndpoint: "/admin/vendors",
    dataKey: "vendors",
    singularKey: "vendor",
    label: "Vendors",
    singularLabel: "Vendor",
    fields: [
      { key: "company_name", label: "Company Name", type: "text", required: true, placeholder: "Company name" },
      { key: "email", label: "Email", type: "email", required: true, placeholder: "vendor@example.com" },
      { key: "phone", label: "Phone", type: "text", placeholder: "+1 (555) 000-0000" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "pending", label: "Pending" },
        { value: "approved", label: "Approved" },
        { value: "suspended", label: "Suspended" },
      ]},
      { key: "description", label: "Description", type: "textarea", placeholder: "Vendor description" },
    ],
    defaultValues: { company_name: "", email: "", phone: "", status: "pending", description: "" },
  },

  commissions: {
    moduleKey: "commissions",
    apiEndpoint: "/admin/commissions",
    dataKey: "commissions",
    singularKey: "commission",
    label: "Commissions",
    singularLabel: "Commission",
    fields: [
      { key: "vendor_id", label: "Vendor ID", type: "text", required: true, placeholder: "Vendor ID" },
      { key: "rate", label: "Rate", type: "number", required: true, placeholder: "0" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "percentage", label: "Percentage" },
        { value: "flat", label: "Flat" },
      ]},
      { key: "min_order", label: "Minimum Order", type: "number", placeholder: "0" },
      { key: "max_cap", label: "Maximum Cap", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { vendor_id: "", rate: 0, type: "percentage", min_order: 0, max_cap: 0, status: "active" },
  },

  payouts: {
    moduleKey: "payouts",
    apiEndpoint: "/admin/payouts",
    dataKey: "payouts",
    singularKey: "payout",
    label: "Payouts",
    singularLabel: "Payout",
    canCreate: false,
    fields: [
      { key: "vendor", label: "Vendor", type: "text", placeholder: "Vendor name", disabled: true },
      { key: "amount", label: "Amount", type: "number", placeholder: "0", disabled: true },
      { key: "status", label: "Status", type: "select", options: [
        { value: "pending", label: "Pending" },
        { value: "processing", label: "Processing" },
        { value: "completed", label: "Completed" },
        { value: "failed", label: "Failed" },
      ]},
      { key: "period_start", label: "Period Start", type: "date" },
      { key: "period_end", label: "Period End", type: "date" },
      { key: "payment_method", label: "Payment Method", type: "text", placeholder: "Bank transfer, PayPal, etc." },
    ],
    defaultValues: { vendor: "", amount: 0, status: "pending", period_start: "", period_end: "", payment_method: "" },
  },

  auctions: {
    moduleKey: "auctions",
    apiEndpoint: "/admin/auctions",
    dataKey: "auctions",
    singularKey: "auction",
    label: "Auctions",
    singularLabel: "Auction",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Auction title" },
      { key: "product_id", label: "Product ID", type: "text", placeholder: "Associated product ID" },
      { key: "start_price", label: "Start Price", type: "number", required: true, placeholder: "0" },
      { key: "reserve_price", label: "Reserve Price", type: "number", placeholder: "0" },
      { key: "buy_now_price", label: "Buy Now Price", type: "number", placeholder: "0" },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "end_date", label: "End Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "active", label: "Active" },
        { value: "ended", label: "Ended" },
        { value: "cancelled", label: "Cancelled" },
      ]},
      { key: "bid_increment", label: "Bid Increment", type: "number", placeholder: "1" },
    ],
    defaultValues: { title: "", product_id: "", start_price: 0, reserve_price: 0, buy_now_price: 0, start_date: "", end_date: "", status: "draft", bid_increment: 1 },
  },

  bookings: {
    moduleKey: "bookings",
    apiEndpoint: "/admin/bookings",
    dataKey: "bookings",
    singularKey: "booking",
    label: "Bookings",
    singularLabel: "Booking",
    fields: [
      { key: "service_name", label: "Service Name", type: "text", required: true, placeholder: "Service name" },
      { key: "customer_name", label: "Customer Name", type: "text", placeholder: "Customer name" },
      { key: "provider", label: "Provider", type: "text", placeholder: "Provider name" },
      { key: "date", label: "Date", type: "date" },
      { key: "time_slot", label: "Time Slot", type: "text", placeholder: "09:00 AM - 10:00 AM" },
      { key: "duration", label: "Duration (minutes)", type: "number", placeholder: "60" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "pending", label: "Pending" },
        { value: "confirmed", label: "Confirmed" },
        { value: "cancelled", label: "Cancelled" },
        { value: "completed", label: "Completed" },
      ]},
      { key: "notes", label: "Notes", type: "textarea", placeholder: "Booking notes" },
    ],
    defaultValues: { service_name: "", customer_name: "", provider: "", date: "", time_slot: "", duration: 60, status: "pending", notes: "" },
  },

  rentals: {
    moduleKey: "rentals",
    apiEndpoint: "/admin/rentals",
    dataKey: "rentals",
    singularKey: "rental",
    label: "Rentals",
    singularLabel: "Rental",
    fields: [
      { key: "item_name", label: "Item Name", type: "text", required: true, placeholder: "Item name" },
      { key: "category", label: "Category", type: "text", placeholder: "Category" },
      { key: "daily_rate", label: "Daily Rate", type: "number", required: true, placeholder: "0" },
      { key: "weekly_rate", label: "Weekly Rate", type: "number", placeholder: "0" },
      { key: "deposit", label: "Deposit", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "available", label: "Available" },
        { value: "rented", label: "Rented" },
        { value: "maintenance", label: "Maintenance" },
      ]},
      { key: "condition", label: "Condition", type: "text", placeholder: "Good, Fair, Excellent, etc." },
    ],
    defaultValues: { item_name: "", category: "", daily_rate: 0, weekly_rate: 0, deposit: 0, status: "available", condition: "" },
  },

  restaurants: {
    moduleKey: "restaurants",
    apiEndpoint: "/store/admin/restaurants",
    dataKey: "restaurants",
    singularKey: "restaurant",
    label: "Restaurants",
    singularLabel: "Restaurant",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Restaurant name" },
      { key: "cuisine_type", label: "Cuisine Type", type: "text", placeholder: "Italian, Japanese, Mexican, etc." },
      { key: "address", label: "Address", type: "text", placeholder: "Restaurant address" },
      { key: "phone", label: "Phone", type: "text", placeholder: "+1 (555) 000-0000" },
      { key: "operating_hours", label: "Operating Hours", type: "text", placeholder: "Mon-Fri 9AM-10PM" },
      { key: "delivery_radius", label: "Delivery Radius (km)", type: "number", placeholder: "5" },
      { key: "min_order_amount", label: "Min Order Amount", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
        { value: "temporarily_closed", label: "Temporarily Closed" },
      ]},
    ],
    defaultValues: { name: "", cuisine_type: "", address: "", phone: "", operating_hours: "", delivery_radius: 0, min_order_amount: 0, status: "active" },
  },

  grocery: {
    moduleKey: "grocery",
    apiEndpoint: "/store/admin/grocery",
    dataKey: "grocery",
    singularKey: "grocery_item",
    label: "Grocery",
    singularLabel: "Grocery Item",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Item name" },
      { key: "category", label: "Category", type: "text", placeholder: "Fruits, Vegetables, Dairy, etc." },
      { key: "unit_type", label: "Unit Type", type: "select", options: [
        { value: "kg", label: "Kilogram (kg)" },
        { value: "liter", label: "Liter" },
        { value: "piece", label: "Piece" },
        { value: "pack", label: "Pack" },
      ]},
      { key: "price", label: "Price", type: "number", required: true, placeholder: "0" },
      { key: "stock_quantity", label: "Stock Quantity", type: "number", placeholder: "0" },
      { key: "is_organic", label: "Organic", type: "checkbox", placeholder: "This item is organic" },
      { key: "shelf_life_days", label: "Shelf Life (days)", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "available", label: "Available" },
        { value: "out_of_stock", label: "Out of Stock" },
        { value: "discontinued", label: "Discontinued" },
      ]},
    ],
    defaultValues: { name: "", category: "", unit_type: "piece", price: 0, stock_quantity: 0, is_organic: false, shelf_life_days: 0, status: "available" },
  },

  travel: {
    moduleKey: "travel",
    apiEndpoint: "/store/admin/travel",
    dataKey: "travel",
    singularKey: "travel_package",
    label: "Travel",
    singularLabel: "Travel Package",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Package name" },
      { key: "destination", label: "Destination", type: "text", required: true, placeholder: "Destination" },
      { key: "package_type", label: "Package Type", type: "select", options: [
        { value: "flight", label: "Flight" },
        { value: "hotel", label: "Hotel" },
        { value: "package", label: "Package" },
        { value: "activity", label: "Activity" },
      ]},
      { key: "duration", label: "Duration", type: "text", placeholder: "7 days / 6 nights" },
      { key: "price", label: "Price", type: "number", required: true, placeholder: "0" },
      { key: "max_travelers", label: "Max Travelers", type: "number", placeholder: "0" },
      { key: "availability_start", label: "Availability Start", type: "date" },
      { key: "availability_end", label: "Availability End", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "available", label: "Available" },
        { value: "booked", label: "Booked" },
        { value: "cancelled", label: "Cancelled" },
      ]},
    ],
    defaultValues: { name: "", destination: "", package_type: "package", duration: "", price: 0, max_travelers: 0, availability_start: "", availability_end: "", status: "available" },
  },

  automotive: {
    moduleKey: "automotive",
    apiEndpoint: "/store/admin/automotive",
    dataKey: "automotive",
    singularKey: "vehicle",
    label: "Automotive",
    singularLabel: "Vehicle",
    fields: [
      { key: "make", label: "Make", type: "text", required: true, placeholder: "Toyota, Ford, etc." },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Camry, F-150, etc." },
      { key: "year", label: "Year", type: "number", placeholder: "2024" },
      { key: "vin", label: "VIN", type: "text", placeholder: "Vehicle Identification Number" },
      { key: "price", label: "Price", type: "number", required: true, placeholder: "0" },
      { key: "mileage", label: "Mileage", type: "number", placeholder: "0" },
      { key: "condition", label: "Condition", type: "select", options: [
        { value: "new", label: "New" },
        { value: "used", label: "Used" },
        { value: "certified", label: "Certified Pre-Owned" },
      ]},
      { key: "fuel_type", label: "Fuel Type", type: "select", options: [
        { value: "gasoline", label: "Gasoline" },
        { value: "diesel", label: "Diesel" },
        { value: "electric", label: "Electric" },
        { value: "hybrid", label: "Hybrid" },
      ]},
      { key: "transmission", label: "Transmission", type: "select", options: [
        { value: "automatic", label: "Automatic" },
        { value: "manual", label: "Manual" },
        { value: "cvt", label: "CVT" },
      ]},
      { key: "status", label: "Status", type: "select", options: [
        { value: "available", label: "Available" },
        { value: "sold", label: "Sold" },
        { value: "reserved", label: "Reserved" },
      ]},
    ],
    defaultValues: { make: "", model: "", year: 2024, vin: "", price: 0, mileage: 0, condition: "new", fuel_type: "gasoline", transmission: "automatic", status: "available" },
  },

  healthcare: {
    moduleKey: "healthcare",
    apiEndpoint: "/store/admin/healthcare",
    dataKey: "healthcare",
    singularKey: "provider",
    label: "Healthcare",
    singularLabel: "Healthcare Provider",
    fields: [
      { key: "provider_name", label: "Provider Name", type: "text", required: true, placeholder: "Provider name" },
      { key: "specialty", label: "Specialty", type: "text", required: true, placeholder: "Cardiology, Dermatology, etc." },
      { key: "license_number", label: "License Number", type: "text", placeholder: "License number" },
      { key: "consultation_fee", label: "Consultation Fee", type: "number", placeholder: "0" },
      { key: "availability", label: "Availability", type: "text", placeholder: "Mon-Fri 9AM-5PM" },
      { key: "accepts_insurance", label: "Accepts Insurance", type: "checkbox", placeholder: "Provider accepts insurance" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { provider_name: "", specialty: "", license_number: "", consultation_fee: 0, availability: "", accepts_insurance: false, status: "active" },
  },

  education: {
    moduleKey: "education",
    apiEndpoint: "/store/admin/education",
    dataKey: "education",
    singularKey: "course",
    label: "Education",
    singularLabel: "Course",
    fields: [
      { key: "course_title", label: "Course Title", type: "text", required: true, placeholder: "Course title" },
      { key: "instructor", label: "Instructor", type: "text", placeholder: "Instructor name" },
      { key: "category", label: "Category", type: "text", placeholder: "Programming, Design, Business, etc." },
      { key: "duration", label: "Duration", type: "text", placeholder: "8 weeks" },
      { key: "price", label: "Price", type: "number", placeholder: "0" },
      { key: "level", label: "Level", type: "select", options: [
        { value: "beginner", label: "Beginner" },
        { value: "intermediate", label: "Intermediate" },
        { value: "advanced", label: "Advanced" },
      ]},
      { key: "max_students", label: "Max Students", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "draft", label: "Draft" },
        { value: "archived", label: "Archived" },
      ]},
    ],
    defaultValues: { course_title: "", instructor: "", category: "", duration: "", price: 0, level: "beginner", max_students: 0, status: "active" },
  },

  fitness: {
    moduleKey: "fitness",
    apiEndpoint: "/store/admin/fitness",
    dataKey: "fitness",
    singularKey: "class",
    label: "Fitness",
    singularLabel: "Fitness Class",
    fields: [
      { key: "class_name", label: "Class Name", type: "text", required: true, placeholder: "Class name" },
      { key: "instructor", label: "Instructor", type: "text", placeholder: "Instructor name" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "yoga", label: "Yoga" },
        { value: "cardio", label: "Cardio" },
        { value: "strength", label: "Strength" },
        { value: "dance", label: "Dance" },
        { value: "martial_arts", label: "Martial Arts" },
      ]},
      { key: "duration", label: "Duration (minutes)", type: "number", placeholder: "60" },
      { key: "capacity", label: "Capacity", type: "number", placeholder: "0" },
      { key: "price", label: "Price", type: "number", placeholder: "0" },
      { key: "schedule", label: "Schedule", type: "text", placeholder: "Mon/Wed/Fri 9:00 AM" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { class_name: "", instructor: "", type: "yoga", duration: 60, capacity: 0, price: 0, schedule: "", status: "active" },
  },

  memberships: {
    moduleKey: "memberships",
    apiEndpoint: "/admin/memberships",
    dataKey: "memberships",
    singularKey: "membership",
    label: "Memberships",
    singularLabel: "Membership",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Membership name" },
      { key: "tier", label: "Tier", type: "select", options: [
        { value: "bronze", label: "Bronze" },
        { value: "silver", label: "Silver" },
        { value: "gold", label: "Gold" },
        { value: "platinum", label: "Platinum" },
      ]},
      { key: "price_monthly", label: "Monthly Price", type: "number", placeholder: "0" },
      { key: "price_yearly", label: "Yearly Price", type: "number", placeholder: "0" },
      { key: "benefits", label: "Benefits", type: "textarea", placeholder: "List of membership benefits" },
      { key: "max_members", label: "Max Members", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { name: "", tier: "bronze", price_monthly: 0, price_yearly: 0, benefits: "", max_members: 0, status: "active" },
  },

  parking: {
    moduleKey: "parking",
    apiEndpoint: "/store/admin/parking",
    dataKey: "parking",
    singularKey: "parking_lot",
    label: "Parking",
    singularLabel: "Parking Lot",
    fields: [
      { key: "lot_name", label: "Lot Name", type: "text", required: true, placeholder: "Parking lot name" },
      { key: "location", label: "Location", type: "text", required: true, placeholder: "Parking location" },
      { key: "spot_type", label: "Spot Type", type: "select", options: [
        { value: "standard", label: "Standard" },
        { value: "handicap", label: "Handicap" },
        { value: "ev_charging", label: "EV Charging" },
        { value: "vip", label: "VIP" },
      ]},
      { key: "hourly_rate", label: "Hourly Rate", type: "number", placeholder: "0" },
      { key: "daily_rate", label: "Daily Rate", type: "number", placeholder: "0" },
      { key: "total_spots", label: "Total Spots", type: "number", required: true, placeholder: "0" },
      { key: "available_spots", label: "Available Spots", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "full", label: "Full" },
        { value: "maintenance", label: "Maintenance" },
      ]},
    ],
    defaultValues: { lot_name: "", location: "", spot_type: "standard", hourly_rate: 0, daily_rate: 0, total_spots: 0, available_spots: 0, status: "active" },
  },

  freelance: {
    moduleKey: "freelance",
    apiEndpoint: "/store/admin/freelance",
    dataKey: "freelance",
    singularKey: "freelancer",
    label: "Freelance",
    singularLabel: "Freelancer",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Service title" },
      { key: "category", label: "Category", type: "text", placeholder: "Web Development, Design, Writing, etc." },
      { key: "hourly_rate", label: "Hourly Rate", type: "number", placeholder: "0" },
      { key: "fixed_price", label: "Fixed Price", type: "number", placeholder: "0" },
      { key: "experience_level", label: "Experience Level", type: "select", options: [
        { value: "entry", label: "Entry Level" },
        { value: "intermediate", label: "Intermediate" },
        { value: "expert", label: "Expert" },
      ]},
      { key: "skills", label: "Skills", type: "textarea", placeholder: "List of skills (comma separated)" },
      { key: "portfolio_url", label: "Portfolio URL", type: "url", placeholder: "https://portfolio.example.com" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
        { value: "suspended", label: "Suspended" },
      ]},
    ],
    defaultValues: { title: "", category: "", hourly_rate: 0, fixed_price: 0, experience_level: "intermediate", skills: "", portfolio_url: "", status: "active" },
  },

  advertising: {
    moduleKey: "advertising",
    apiEndpoint: "/admin/advertising",
    dataKey: "campaigns",
    singularKey: "campaign",
    label: "Advertising",
    singularLabel: "Campaign",
    fields: [
      { key: "campaign_name", label: "Campaign Name", type: "text", required: true, placeholder: "Campaign name" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "banner", label: "Banner" },
        { value: "native", label: "Native" },
        { value: "video", label: "Video" },
        { value: "sponsored", label: "Sponsored" },
      ]},
      { key: "budget", label: "Budget", type: "number", placeholder: "0" },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "end_date", label: "End Date", type: "date" },
      { key: "target_audience", label: "Target Audience", type: "text", placeholder: "Target audience description" },
      { key: "impressions_goal", label: "Impressions Goal", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "active", label: "Active" },
        { value: "paused", label: "Paused" },
        { value: "completed", label: "Completed" },
      ]},
    ],
    defaultValues: { campaign_name: "", type: "banner", budget: 0, start_date: "", end_date: "", target_audience: "", impressions_goal: 0, status: "draft" },
  },

  affiliates: {
    moduleKey: "affiliates",
    apiEndpoint: "/admin/affiliates",
    dataKey: "affiliates",
    singularKey: "affiliate",
    label: "Affiliates",
    singularLabel: "Affiliate",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Affiliate name" },
      { key: "email", label: "Email", type: "email", required: true, placeholder: "affiliate@example.com" },
      { key: "commission_rate", label: "Commission Rate (%)", type: "number", placeholder: "0" },
      { key: "referral_code", label: "Referral Code", type: "text", placeholder: "REF-001" },
      { key: "total_referrals", label: "Total Referrals", type: "number", placeholder: "0", disabled: true },
      { key: "total_earned", label: "Total Earned", type: "number", placeholder: "0", disabled: true },
      { key: "payout_method", label: "Payout Method", type: "select", options: [
        { value: "bank_transfer", label: "Bank Transfer" },
        { value: "paypal", label: "PayPal" },
        { value: "stripe", label: "Stripe" },
        { value: "check", label: "Check" },
      ]},
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
        { value: "pending", label: "Pending" },
      ]},
    ],
    defaultValues: { name: "", email: "", commission_rate: 0, referral_code: "", total_referrals: 0, total_earned: 0, payout_method: "bank_transfer", status: "pending" },
  },

  promotions: {
    moduleKey: "promotions",
    apiEndpoint: "/admin/promotions",
    dataKey: "promotions",
    singularKey: "promotion",
    label: "Promotions",
    singularLabel: "Promotion",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Promotion name" },
      { key: "code", label: "Code", type: "text", required: true, placeholder: "PROMO2024" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "percentage", label: "Percentage" },
        { value: "fixed", label: "Fixed Amount" },
        { value: "bogo", label: "Buy One Get One" },
        { value: "free_shipping", label: "Free Shipping" },
      ]},
      { key: "value", label: "Value", type: "number", required: true, placeholder: "0" },
      { key: "min_purchase", label: "Minimum Purchase", type: "number", placeholder: "0" },
      { key: "max_uses", label: "Max Uses", type: "number", placeholder: "0" },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "end_date", label: "End Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
        { value: "expired", label: "Expired" },
      ]},
    ],
    defaultValues: { name: "", code: "", type: "percentage", value: 0, min_purchase: 0, max_uses: 0, start_date: "", end_date: "", status: "active" },
  },

  crowdfunding: {
    moduleKey: "crowdfunding",
    apiEndpoint: "/store/admin/crowdfunding",
    dataKey: "campaigns",
    singularKey: "campaign",
    label: "Crowdfunding",
    singularLabel: "Campaign",
    fields: [
      { key: "campaign_name", label: "Campaign Name", type: "text", required: true, placeholder: "Campaign name" },
      { key: "goal_amount", label: "Goal Amount", type: "number", required: true, placeholder: "0" },
      { key: "raised_amount", label: "Raised Amount", type: "number", placeholder: "0", disabled: true },
      { key: "backer_count", label: "Backer Count", type: "number", placeholder: "0", disabled: true },
      { key: "category", label: "Category", type: "text", placeholder: "Technology, Art, Film, etc." },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "end_date", label: "End Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "active", label: "Active" },
        { value: "funded", label: "Funded" },
        { value: "failed", label: "Failed" },
      ]},
    ],
    defaultValues: { campaign_name: "", goal_amount: 0, raised_amount: 0, backer_count: 0, category: "", start_date: "", end_date: "", status: "draft" },
  },

  charity: {
    moduleKey: "charity",
    apiEndpoint: "/store/admin/charity",
    dataKey: "campaigns",
    singularKey: "campaign",
    label: "Charity",
    singularLabel: "Charity Campaign",
    fields: [
      { key: "campaign_name", label: "Campaign Name", type: "text", required: true, placeholder: "Campaign name" },
      { key: "organization", label: "Organization", type: "text", required: true, placeholder: "Organization name" },
      { key: "goal_amount", label: "Goal Amount", type: "number", placeholder: "0" },
      { key: "raised_amount", label: "Raised Amount", type: "number", placeholder: "0", disabled: true },
      { key: "category", label: "Category", type: "text", placeholder: "Health, Education, Environment, etc." },
      { key: "description", label: "Description", type: "textarea", placeholder: "Campaign description" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "completed", label: "Completed" },
        { value: "closed", label: "Closed" },
      ]},
    ],
    defaultValues: { campaign_name: "", organization: "", goal_amount: 0, raised_amount: 0, category: "", description: "", status: "active" },
  },

  classifieds: {
    moduleKey: "classifieds",
    apiEndpoint: "/admin/classifieds",
    dataKey: "listings",
    singularKey: "listing",
    label: "Classifieds",
    singularLabel: "Classified Listing",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Listing title" },
      { key: "category", label: "Category", type: "text", placeholder: "Category" },
      { key: "price", label: "Price", type: "number", placeholder: "0" },
      { key: "condition", label: "Condition", type: "select", options: [
        { value: "new", label: "New" },
        { value: "used", label: "Used" },
        { value: "refurbished", label: "Refurbished" },
      ]},
      { key: "location", label: "Location", type: "text", placeholder: "Location" },
      { key: "contact_method", label: "Contact Method", type: "select", options: [
        { value: "email", label: "Email" },
        { value: "phone", label: "Phone" },
        { value: "chat", label: "Chat" },
      ]},
      { key: "expiry_date", label: "Expiry Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "sold", label: "Sold" },
        { value: "expired", label: "Expired" },
      ]},
    ],
    defaultValues: { title: "", category: "", price: 0, condition: "used", location: "", contact_method: "email", expiry_date: "", status: "active" },
  },

  quotes: {
    moduleKey: "quotes",
    apiEndpoint: "/admin/quotes",
    dataKey: "quotes",
    singularKey: "quote",
    label: "Quotes",
    singularLabel: "Quote",
    fields: [
      { key: "quote_number", label: "Quote Number", type: "text", placeholder: "QT-0001" },
      { key: "company", label: "Company", type: "text", required: true, placeholder: "Company name" },
      { key: "customer_email", label: "Customer Email", type: "email", placeholder: "customer@example.com" },
      { key: "items_count", label: "Items Count", type: "number", placeholder: "0" },
      { key: "total_amount", label: "Total Amount", type: "number", placeholder: "0" },
      { key: "valid_until", label: "Valid Until", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "sent", label: "Sent" },
        { value: "accepted", label: "Accepted" },
        { value: "rejected", label: "Rejected" },
        { value: "expired", label: "Expired" },
      ]},
    ],
    defaultValues: { quote_number: "", company: "", customer_email: "", items_count: 0, total_amount: 0, valid_until: "", status: "draft" },
  },

  invoices: {
    moduleKey: "invoices",
    apiEndpoint: "/admin/invoices",
    dataKey: "invoices",
    singularKey: "invoice",
    label: "Invoices",
    singularLabel: "Invoice",
    fields: [
      { key: "invoice_number", label: "Invoice Number", type: "text", placeholder: "INV-0001" },
      { key: "customer", label: "Customer", type: "text", required: true, placeholder: "Customer name" },
      { key: "amount", label: "Amount", type: "number", required: true, placeholder: "0" },
      { key: "tax", label: "Tax", type: "number", placeholder: "0" },
      { key: "total", label: "Total", type: "number", placeholder: "0" },
      { key: "due_date", label: "Due Date", type: "date" },
      { key: "payment_status", label: "Payment Status", type: "select", options: [
        { value: "unpaid", label: "Unpaid" },
        { value: "partial", label: "Partial" },
        { value: "paid", label: "Paid" },
        { value: "overdue", label: "Overdue" },
      ]},
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "sent", label: "Sent" },
        { value: "cancelled", label: "Cancelled" },
      ]},
    ],
    defaultValues: { invoice_number: "", customer: "", amount: 0, tax: 0, total: 0, due_date: "", payment_status: "unpaid", status: "draft" },
  },

  subscriptions: {
    moduleKey: "subscriptions",
    apiEndpoint: "/admin/subscriptions",
    dataKey: "subscriptions",
    singularKey: "subscription",
    label: "Subscriptions",
    singularLabel: "Subscription",
    fields: [
      { key: "plan_name", label: "Plan Name", type: "text", required: true, placeholder: "Plan name" },
      { key: "customer", label: "Customer", type: "text", placeholder: "Customer name" },
      { key: "price", label: "Price", type: "number", required: true, placeholder: "0" },
      { key: "billing_cycle", label: "Billing Cycle", type: "select", options: [
        { value: "monthly", label: "Monthly" },
        { value: "quarterly", label: "Quarterly" },
        { value: "yearly", label: "Yearly" },
      ]},
      { key: "next_billing_date", label: "Next Billing Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "paused", label: "Paused" },
        { value: "cancelled", label: "Cancelled" },
        { value: "expired", label: "Expired" },
      ]},
    ],
    defaultValues: { plan_name: "", customer: "", price: 0, billing_cycle: "monthly", next_billing_date: "", status: "active" },
  },

  reviews: {
    moduleKey: "reviews",
    apiEndpoint: "/admin/reviews",
    dataKey: "reviews",
    singularKey: "review",
    label: "Reviews",
    singularLabel: "Review",
    canCreate: false,
    fields: [
      { key: "product", label: "Product", type: "text", placeholder: "Product name", disabled: true },
      { key: "customer", label: "Customer", type: "text", placeholder: "Customer name", disabled: true },
      { key: "rating", label: "Rating (1-5)", type: "number", placeholder: "5" },
      { key: "title", label: "Title", type: "text", placeholder: "Review title" },
      { key: "content", label: "Content", type: "textarea", placeholder: "Review content" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "pending", label: "Pending" },
        { value: "approved", label: "Approved" },
        { value: "rejected", label: "Rejected" },
      ]},
    ],
    defaultValues: { product: "", customer: "", rating: 5, title: "", content: "", status: "pending" },
  },

  team: {
    moduleKey: "team",
    apiEndpoint: "/admin/team",
    dataKey: "members",
    singularKey: "member",
    label: "Team",
    singularLabel: "Team Member",
    canDelete: false,
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Full name" },
      { key: "email", label: "Email", type: "email", required: true, placeholder: "email@example.com" },
      { key: "role", label: "Role", type: "select", options: [
        { value: "super_admin", label: "Super Admin" },
        { value: "admin", label: "Admin" },
        { value: "manager", label: "Manager" },
        { value: "editor", label: "Editor" },
        { value: "moderator", label: "Moderator" },
        { value: "support", label: "Support" },
        { value: "analyst", label: "Analyst" },
        { value: "developer", label: "Developer" },
        { value: "viewer", label: "Viewer" },
        { value: "vendor_manager", label: "Vendor Manager" },
      ]},
      { key: "department", label: "Department", type: "text", placeholder: "Engineering, Marketing, Sales, etc." },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { name: "", email: "", role: "viewer", department: "", status: "active" },
  },

  companies: {
    moduleKey: "companies",
    apiEndpoint: "/admin/companies",
    dataKey: "companies",
    singularKey: "company",
    label: "Companies",
    singularLabel: "Company",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Company name" },
      { key: "registration_number", label: "Registration Number", type: "text", placeholder: "Registration number" },
      { key: "tax_id", label: "Tax ID", type: "text", placeholder: "Tax identification number" },
      { key: "industry", label: "Industry", type: "text", placeholder: "Technology, Healthcare, Retail, etc." },
      { key: "size", label: "Size", type: "select", options: [
        { value: "small", label: "Small" },
        { value: "medium", label: "Medium" },
        { value: "large", label: "Large" },
        { value: "enterprise", label: "Enterprise" },
      ]},
      { key: "address", label: "Address", type: "textarea", placeholder: "Company address" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
        { value: "pending", label: "Pending" },
      ]},
    ],
    defaultValues: { name: "", registration_number: "", tax_id: "", industry: "", size: "small", address: "", status: "active" },
  },

  stores: {
    moduleKey: "stores",
    apiEndpoint: "/admin/stores",
    dataKey: "stores",
    singularKey: "store",
    label: "Stores",
    singularLabel: "Store",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Store name" },
      { key: "handle", label: "Handle", type: "text", placeholder: "store-handle" },
      { key: "default_currency", label: "Default Currency", type: "select", options: [
        { value: "USD", label: "USD" },
        { value: "EUR", label: "EUR" },
        { value: "GBP", label: "GBP" },
        { value: "CAD", label: "CAD" },
        { value: "AUD", label: "AUD" },
        { value: "JPY", label: "JPY" },
      ]},
      { key: "default_locale", label: "Default Locale", type: "select", options: [
        { value: "en", label: "English" },
        { value: "es", label: "Spanish" },
        { value: "fr", label: "French" },
        { value: "de", label: "German" },
        { value: "ja", label: "Japanese" },
        { value: "zh", label: "Chinese" },
      ]},
      { key: "subdomain", label: "Subdomain", type: "text", placeholder: "my-store" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { name: "", handle: "", default_currency: "USD", default_locale: "en", subdomain: "", status: "active" },
  },

  legal: {
    moduleKey: "legal",
    apiEndpoint: "/admin/legal",
    dataKey: "documents",
    singularKey: "document",
    label: "Legal",
    singularLabel: "Legal Document",
    fields: [
      { key: "document_title", label: "Document Title", type: "text", required: true, placeholder: "Document title" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "terms", label: "Terms of Service" },
        { value: "privacy", label: "Privacy Policy" },
        { value: "refund", label: "Refund Policy" },
        { value: "shipping", label: "Shipping Policy" },
        { value: "cookies", label: "Cookie Policy" },
      ]},
      { key: "version", label: "Version", type: "text", placeholder: "1.0.0" },
      { key: "effective_date", label: "Effective Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "published", label: "Published" },
        { value: "archived", label: "Archived" },
      ]},
    ],
    defaultValues: { document_title: "", type: "terms", version: "", effective_date: "", status: "draft" },
  },

  utilities: {
    moduleKey: "utilities",
    apiEndpoint: "/store/admin/utilities",
    dataKey: "services",
    singularKey: "service",
    label: "Utilities",
    singularLabel: "Utility Service",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Service name" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "water", label: "Water" },
        { value: "electricity", label: "Electricity" },
        { value: "gas", label: "Gas" },
        { value: "internet", label: "Internet" },
        { value: "telecom", label: "Telecom" },
      ]},
      { key: "provider", label: "Provider", type: "text", placeholder: "Provider name" },
      { key: "account_number", label: "Account Number", type: "text", placeholder: "Account number" },
      { key: "billing_cycle", label: "Billing Cycle", type: "select", options: [
        { value: "monthly", label: "Monthly" },
        { value: "quarterly", label: "Quarterly" },
        { value: "yearly", label: "Yearly" },
      ]},
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { name: "", type: "electricity", provider: "", account_number: "", billing_cycle: "monthly", status: "active" },
  },

  settings: {
    moduleKey: "settings",
    apiEndpoint: "/admin/settings",
    dataKey: "settings",
    singularKey: "setting",
    label: "Settings",
    singularLabel: "Settings",
    canCreate: false,
    canDelete: false,
    fields: [
      { key: "store_name", label: "Store Name", type: "text", required: true, placeholder: "Your store name" },
      { key: "contact_email", label: "Contact Email", type: "email", required: true, placeholder: "contact@store.com" },
      { key: "currency", label: "Currency", type: "select", options: [
        { value: "USD", label: "USD" },
        { value: "EUR", label: "EUR" },
        { value: "GBP", label: "GBP" },
        { value: "CAD", label: "CAD" },
        { value: "AUD", label: "AUD" },
        { value: "JPY", label: "JPY" },
      ]},
      { key: "timezone", label: "Timezone", type: "select", options: [
        { value: "America/New_York", label: "Eastern Time (ET)" },
        { value: "America/Chicago", label: "Central Time (CT)" },
        { value: "America/Denver", label: "Mountain Time (MT)" },
        { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
        { value: "Europe/London", label: "GMT" },
        { value: "Europe/Paris", label: "Central European (CET)" },
        { value: "Asia/Tokyo", label: "Japan (JST)" },
        { value: "Asia/Shanghai", label: "China (CST)" },
        { value: "UTC", label: "UTC" },
      ]},
      { key: "language", label: "Language", type: "select", options: [
        { value: "en", label: "English" },
        { value: "es", label: "Spanish" },
        { value: "fr", label: "French" },
        { value: "de", label: "German" },
        { value: "ja", label: "Japanese" },
        { value: "zh", label: "Chinese" },
      ]},
      { key: "maintenance_mode", label: "Maintenance Mode", type: "checkbox", placeholder: "Enable maintenance mode" },
    ],
    defaultValues: { store_name: "", contact_email: "", currency: "USD", timezone: "UTC", language: "en", maintenance_mode: false },
  },

  "digital-products": {
    moduleKey: "digital-products",
    apiEndpoint: "/admin/digital-products",
    dataKey: "products",
    singularKey: "product",
    label: "Digital Products",
    singularLabel: "Digital Product",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Product title" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Product description" },
      { key: "price", label: "Price", type: "number", required: true, placeholder: "0" },
      { key: "file_url", label: "File URL", type: "url", placeholder: "https://example.com/file.zip" },
      { key: "format", label: "Format", type: "text", placeholder: "PDF, ZIP, MP3, etc." },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "draft", label: "Draft" },
        { value: "archived", label: "Archived" },
      ]},
    ],
    defaultValues: { title: "", description: "", price: 0, file_url: "", format: "", status: "active" },
  },

  "event-ticketing": {
    moduleKey: "event-ticketing",
    apiEndpoint: "/admin/events",
    dataKey: "events",
    singularKey: "event",
    label: "Event Ticketing",
    singularLabel: "Event",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Event title" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Event description" },
      { key: "venue", label: "Venue", type: "text", placeholder: "Venue name" },
      { key: "date", label: "Date", type: "date" },
      { key: "capacity", label: "Capacity", type: "number", placeholder: "0" },
      { key: "price", label: "Price", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "published", label: "Published" },
        { value: "sold-out", label: "Sold Out" },
        { value: "cancelled", label: "Cancelled" },
      ]},
    ],
    defaultValues: { title: "", description: "", venue: "", date: "", capacity: 0, price: 0, status: "draft" },
  },

  "financial-products": {
    moduleKey: "financial-products",
    apiEndpoint: "/admin/financial-products",
    dataKey: "products",
    singularKey: "product",
    label: "Financial Products",
    singularLabel: "Financial Product",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, placeholder: "Product name" },
      { key: "type", label: "Type", type: "select", options: [
        { value: "insurance", label: "Insurance" },
        { value: "loan", label: "Loan" },
        { value: "investment", label: "Investment" },
        { value: "savings", label: "Savings" },
      ]},
      { key: "description", label: "Description", type: "textarea", placeholder: "Product description" },
      { key: "rate", label: "Rate", type: "number", placeholder: "0" },
      { key: "min_amount", label: "Minimum Amount", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
    ],
    defaultValues: { name: "", type: "insurance", description: "", rate: 0, min_amount: 0, status: "active" },
  },

  "pet-services": {
    moduleKey: "pet-services",
    apiEndpoint: "/admin/pet-services",
    dataKey: "services",
    singularKey: "service",
    label: "Pet Services",
    singularLabel: "Pet Service",
    fields: [
      { key: "service_name", label: "Service Name", type: "text", required: true, placeholder: "Service name" },
      { key: "pet_type", label: "Pet Type", type: "select", options: [
        { value: "dog", label: "Dog" },
        { value: "cat", label: "Cat" },
        { value: "bird", label: "Bird" },
        { value: "other", label: "Other" },
      ]},
      { key: "price", label: "Price", type: "number", placeholder: "0" },
      { key: "duration", label: "Duration", type: "text", placeholder: "30 minutes" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ]},
      { key: "description", label: "Description", type: "textarea", placeholder: "Service description" },
    ],
    defaultValues: { service_name: "", pet_type: "dog", price: 0, duration: "", status: "active", description: "" },
  },

  "real-estate": {
    moduleKey: "real-estate",
    apiEndpoint: "/admin/real-estate",
    dataKey: "listings",
    singularKey: "listing",
    label: "Real Estate",
    singularLabel: "Listing",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Listing title" },
      { key: "address", label: "Address", type: "text", required: true, placeholder: "Property address" },
      { key: "property_type", label: "Property Type", type: "select", options: [
        { value: "residential", label: "Residential" },
        { value: "commercial", label: "Commercial" },
        { value: "industrial", label: "Industrial" },
        { value: "land", label: "Land" },
      ]},
      { key: "price", label: "Price", type: "number", required: true, placeholder: "0" },
      { key: "area", label: "Area (sq ft)", type: "number", placeholder: "0" },
      { key: "bedrooms", label: "Bedrooms", type: "number", placeholder: "0" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "available", label: "Available" },
        { value: "sold", label: "Sold" },
        { value: "rented", label: "Rented" },
        { value: "pending", label: "Pending" },
      ]},
    ],
    defaultValues: { title: "", address: "", property_type: "residential", price: 0, area: 0, bedrooms: 0, status: "available" },
  },

  "social-commerce": {
    moduleKey: "social-commerce",
    apiEndpoint: "/admin/social-commerce",
    dataKey: "posts",
    singularKey: "post",
    label: "Social Commerce",
    singularLabel: "Social Post",
    fields: [
      { key: "title", label: "Title", type: "text", required: true, placeholder: "Post title" },
      { key: "platform", label: "Platform", type: "select", options: [
        { value: "instagram", label: "Instagram" },
        { value: "facebook", label: "Facebook" },
        { value: "tiktok", label: "TikTok" },
        { value: "twitter", label: "Twitter" },
      ]},
      { key: "content", label: "Content", type: "textarea", placeholder: "Post content" },
      { key: "product_link", label: "Product Link", type: "url", placeholder: "https://example.com/product" },
      { key: "status", label: "Status", type: "select", options: [
        { value: "draft", label: "Draft" },
        { value: "published", label: "Published" },
        { value: "archived", label: "Archived" },
      ]},
    ],
    defaultValues: { title: "", platform: "instagram", content: "", product_link: "", status: "draft" },
  },
}
