/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeStoresRouteImport } from './routes/$countryCode/stores'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeSlugRouteImport } from './routes/$countryCode/$slug'
import { Route as CountryCodeVendorIndexRouteImport } from './routes/$countryCode/vendor/index'
import { Route as CountryCodeQuotesIndexRouteImport } from './routes/$countryCode/quotes/index'
import { Route as CountryCodeVendorPayoutsRouteImport } from './routes/$countryCode/vendor/payouts'
import { Route as CountryCodeVendorCommissionsRouteImport } from './routes/$countryCode/vendor/commissions'
import { Route as CountryCodeQuotesRequestRouteImport } from './routes/$countryCode/quotes/request'
import { Route as CountryCodeQuotesIdRouteImport } from './routes/$countryCode/quotes/$id'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeB2bRegisterRouteImport } from './routes/$countryCode/b2b/register'
import { Route as CountryCodeVendorProductsIndexRouteImport } from './routes/$countryCode/vendor/products/index'
import { Route as CountryCodeVendorOrdersIndexRouteImport } from './routes/$countryCode/vendor/orders/index'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'
import { ServerRoute as HealthServerRouteImport } from './routes/health'

const rootServerRouteImport = createServerRootRoute()

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoresRoute = CountryCodeStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeSlugRoute = CountryCodeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorIndexRoute = CountryCodeVendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeQuotesIndexRoute = CountryCodeQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorPayoutsRoute =
  CountryCodeVendorPayoutsRouteImport.update({
    id: '/vendor/payouts',
    path: '/vendor/payouts',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorCommissionsRoute =
  CountryCodeVendorCommissionsRouteImport.update({
    id: '/vendor/commissions',
    path: '/vendor/commissions',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeQuotesRequestRoute =
  CountryCodeQuotesRequestRouteImport.update({
    id: '/quotes/request',
    path: '/quotes/request',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeQuotesIdRoute = CountryCodeQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeB2bRegisterRoute = CountryCodeB2bRegisterRouteImport.update({
  id: '/b2b/register',
  path: '/b2b/register',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorProductsIndexRoute =
  CountryCodeVendorProductsIndexRouteImport.update({
    id: '/vendor/products/',
    path: '/vendor/products/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorOrdersIndexRoute =
  CountryCodeVendorOrdersIndexRouteImport.update({
    id: '/vendor/orders/',
    path: '/vendor/orders/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const HealthServerRoute = HealthServerRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/store': typeof StoreRoute
  '/$countryCode/$slug': typeof CountryCodeSlugRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/b2b/register': typeof CountryCodeB2bRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quotes/$id': typeof CountryCodeQuotesIdRoute
  '/$countryCode/quotes/request': typeof CountryCodeQuotesRequestRoute
  '/$countryCode/vendor/commissions': typeof CountryCodeVendorCommissionsRoute
  '/$countryCode/vendor/payouts': typeof CountryCodeVendorPayoutsRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesIndexRoute
  '/$countryCode/vendor': typeof CountryCodeVendorIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/vendor/orders': typeof CountryCodeVendorOrdersIndexRoute
  '/$countryCode/vendor/products': typeof CountryCodeVendorProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/store': typeof StoreRoute
  '/$countryCode/$slug': typeof CountryCodeSlugRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/b2b/register': typeof CountryCodeB2bRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quotes/$id': typeof CountryCodeQuotesIdRoute
  '/$countryCode/quotes/request': typeof CountryCodeQuotesRequestRoute
  '/$countryCode/vendor/commissions': typeof CountryCodeVendorCommissionsRoute
  '/$countryCode/vendor/payouts': typeof CountryCodeVendorPayoutsRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesIndexRoute
  '/$countryCode/vendor': typeof CountryCodeVendorIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/vendor/orders': typeof CountryCodeVendorOrdersIndexRoute
  '/$countryCode/vendor/products': typeof CountryCodeVendorProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/store': typeof StoreRoute
  '/$countryCode/$slug': typeof CountryCodeSlugRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/b2b/register': typeof CountryCodeB2bRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quotes/$id': typeof CountryCodeQuotesIdRoute
  '/$countryCode/quotes/request': typeof CountryCodeQuotesRequestRoute
  '/$countryCode/vendor/commissions': typeof CountryCodeVendorCommissionsRoute
  '/$countryCode/vendor/payouts': typeof CountryCodeVendorPayoutsRoute
  '/$countryCode/quotes/': typeof CountryCodeQuotesIndexRoute
  '/$countryCode/vendor/': typeof CountryCodeVendorIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/vendor/orders/': typeof CountryCodeVendorOrdersIndexRoute
  '/$countryCode/vendor/products/': typeof CountryCodeVendorProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/store'
    | '/$countryCode/$slug'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/'
    | '/$countryCode/b2b/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quotes/$id'
    | '/$countryCode/quotes/request'
    | '/$countryCode/vendor/commissions'
    | '/$countryCode/vendor/payouts'
    | '/$countryCode/quotes'
    | '/$countryCode/vendor'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/vendor/orders'
    | '/$countryCode/vendor/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/store'
    | '/$countryCode/$slug'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode'
    | '/$countryCode/b2b/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quotes/$id'
    | '/$countryCode/quotes/request'
    | '/$countryCode/vendor/commissions'
    | '/$countryCode/vendor/payouts'
    | '/$countryCode/quotes'
    | '/$countryCode/vendor'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/vendor/orders'
    | '/$countryCode/vendor/products'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/store'
    | '/$countryCode/$slug'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/'
    | '/$countryCode/b2b/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quotes/$id'
    | '/$countryCode/quotes/request'
    | '/$countryCode/vendor/commissions'
    | '/$countryCode/vendor/payouts'
    | '/$countryCode/quotes/'
    | '/$countryCode/vendor/'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/vendor/orders/'
    | '/$countryCode/vendor/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  StoreRoute: typeof StoreRoute
}
export interface FileServerRoutesByFullPath {
  '/health': typeof HealthServerRoute
}
export interface FileServerRoutesByTo {
  '/health': typeof HealthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/health': typeof HealthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/health'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/health'
  id: '__root__' | '/health'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  HealthServerRoute: typeof HealthServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/stores': {
      id: '/$countryCode/stores'
      path: '/stores'
      fullPath: '/$countryCode/stores'
      preLoaderRoute: typeof CountryCodeStoresRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/$slug': {
      id: '/$countryCode/$slug'
      path: '/$slug'
      fullPath: '/$countryCode/$slug'
      preLoaderRoute: typeof CountryCodeSlugRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/': {
      id: '/$countryCode/vendor/'
      path: '/vendor'
      fullPath: '/$countryCode/vendor'
      preLoaderRoute: typeof CountryCodeVendorIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes/': {
      id: '/$countryCode/quotes/'
      path: '/quotes'
      fullPath: '/$countryCode/quotes'
      preLoaderRoute: typeof CountryCodeQuotesIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/payouts': {
      id: '/$countryCode/vendor/payouts'
      path: '/vendor/payouts'
      fullPath: '/$countryCode/vendor/payouts'
      preLoaderRoute: typeof CountryCodeVendorPayoutsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/commissions': {
      id: '/$countryCode/vendor/commissions'
      path: '/vendor/commissions'
      fullPath: '/$countryCode/vendor/commissions'
      preLoaderRoute: typeof CountryCodeVendorCommissionsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes/request': {
      id: '/$countryCode/quotes/request'
      path: '/quotes/request'
      fullPath: '/$countryCode/quotes/request'
      preLoaderRoute: typeof CountryCodeQuotesRequestRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes/$id': {
      id: '/$countryCode/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/$countryCode/quotes/$id'
      preLoaderRoute: typeof CountryCodeQuotesIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/b2b/register': {
      id: '/$countryCode/b2b/register'
      path: '/b2b/register'
      fullPath: '/$countryCode/b2b/register'
      preLoaderRoute: typeof CountryCodeB2bRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/products/': {
      id: '/$countryCode/vendor/products/'
      path: '/vendor/products'
      fullPath: '/$countryCode/vendor/products'
      preLoaderRoute: typeof CountryCodeVendorProductsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/orders/': {
      id: '/$countryCode/vendor/orders/'
      path: '/vendor/orders'
      fullPath: '/$countryCode/vendor/orders'
      preLoaderRoute: typeof CountryCodeVendorOrdersIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface CountryCodeRouteChildren {
  CountryCodeSlugRoute: typeof CountryCodeSlugRoute
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeStoresRoute: typeof CountryCodeStoresRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeB2bRegisterRoute: typeof CountryCodeB2bRegisterRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeQuotesIdRoute: typeof CountryCodeQuotesIdRoute
  CountryCodeQuotesRequestRoute: typeof CountryCodeQuotesRequestRoute
  CountryCodeVendorCommissionsRoute: typeof CountryCodeVendorCommissionsRoute
  CountryCodeVendorPayoutsRoute: typeof CountryCodeVendorPayoutsRoute
  CountryCodeQuotesIndexRoute: typeof CountryCodeQuotesIndexRoute
  CountryCodeVendorIndexRoute: typeof CountryCodeVendorIndexRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
  CountryCodeVendorOrdersIndexRoute: typeof CountryCodeVendorOrdersIndexRoute
  CountryCodeVendorProductsIndexRoute: typeof CountryCodeVendorProductsIndexRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeSlugRoute: CountryCodeSlugRoute,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeStoresRoute: CountryCodeStoresRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeB2bRegisterRoute: CountryCodeB2bRegisterRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeQuotesIdRoute: CountryCodeQuotesIdRoute,
  CountryCodeQuotesRequestRoute: CountryCodeQuotesRequestRoute,
  CountryCodeVendorCommissionsRoute: CountryCodeVendorCommissionsRoute,
  CountryCodeVendorPayoutsRoute: CountryCodeVendorPayoutsRoute,
  CountryCodeQuotesIndexRoute: CountryCodeQuotesIndexRoute,
  CountryCodeVendorIndexRoute: CountryCodeVendorIndexRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
  CountryCodeVendorOrdersIndexRoute: CountryCodeVendorOrdersIndexRoute,
  CountryCodeVendorProductsIndexRoute: CountryCodeVendorProductsIndexRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  HealthServerRoute: HealthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
