/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeStoresRouteImport } from './routes/$countryCode/stores'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeResetPasswordRouteImport } from './routes/$countryCode/reset-password'
import { Route as CountryCodeRegisterRouteImport } from './routes/$countryCode/register'
import { Route as CountryCodeLoginRouteImport } from './routes/$countryCode/login'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeSlugRouteImport } from './routes/$countryCode/$slug'
import { Route as CountryCodeVendorsIndexRouteImport } from './routes/$countryCode/vendors/index'
import { Route as CountryCodeVendorIndexRouteImport } from './routes/$countryCode/vendor/index'
import { Route as CountryCodeSubscriptionsIndexRouteImport } from './routes/$countryCode/subscriptions/index'
import { Route as CountryCodeQuotesIndexRouteImport } from './routes/$countryCode/quotes/index'
import { Route as CountryCodeBookingsIndexRouteImport } from './routes/$countryCode/bookings/index'
import { Route as CountryCodeAccountIndexRouteImport } from './routes/$countryCode/account/index'
import { Route as CountryCodeVendorsHandleRouteImport } from './routes/$countryCode/vendors/$handle'
import { Route as CountryCodeVendorRegisterRouteImport } from './routes/$countryCode/vendor/register'
import { Route as CountryCodeVendorPayoutsRouteImport } from './routes/$countryCode/vendor/payouts'
import { Route as CountryCodeVendorCommissionsRouteImport } from './routes/$countryCode/vendor/commissions'
import { Route as CountryCodeSubscriptionsSuccessRouteImport } from './routes/$countryCode/subscriptions/success'
import { Route as CountryCodeSubscriptionsCheckoutRouteImport } from './routes/$countryCode/subscriptions/checkout'
import { Route as CountryCodeQuotesRequestRouteImport } from './routes/$countryCode/quotes/request'
import { Route as CountryCodeQuotesIdRouteImport } from './routes/$countryCode/quotes/$id'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeBookingsConfirmationRouteImport } from './routes/$countryCode/bookings/confirmation'
import { Route as CountryCodeBookingsServiceHandleRouteImport } from './routes/$countryCode/bookings/$serviceHandle'
import { Route as CountryCodeB2bRegisterRouteImport } from './routes/$countryCode/b2b/register'
import { Route as CountryCodeB2bDashboardRouteImport } from './routes/$countryCode/b2b/dashboard'
import { Route as CountryCodeAccountSettingsRouteImport } from './routes/$countryCode/account/settings'
import { Route as CountryCodeAccountProfileRouteImport } from './routes/$countryCode/account/profile'
import { Route as CountryCodeAccountAddressesRouteImport } from './routes/$countryCode/account/addresses'
import { Route as CountryCodeVendorProductsIndexRouteImport } from './routes/$countryCode/vendor/products/index'
import { Route as CountryCodeVendorPayoutsIndexRouteImport } from './routes/$countryCode/vendor/payouts/index'
import { Route as CountryCodeVendorOrdersIndexRouteImport } from './routes/$countryCode/vendor/orders/index'
import { Route as CountryCodeAccountSubscriptionsIndexRouteImport } from './routes/$countryCode/account/subscriptions/index'
import { Route as CountryCodeAccountOrdersIndexRouteImport } from './routes/$countryCode/account/orders/index'
import { Route as CountryCodeAccountBookingsIndexRouteImport } from './routes/$countryCode/account/bookings/index'
import { Route as CountryCodeVendorProductsNewRouteImport } from './routes/$countryCode/vendor/products/new'
import { Route as CountryCodeVendorProductsProductIdRouteImport } from './routes/$countryCode/vendor/products/$productId'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'
import { Route as CountryCodeAccountSubscriptionsIdRouteImport } from './routes/$countryCode/account/subscriptions/$id'
import { Route as CountryCodeAccountOrdersIdRouteImport } from './routes/$countryCode/account/orders/$id'
import { Route as CountryCodeAccountBookingsIdRouteImport } from './routes/$countryCode/account/bookings/$id'
import { ServerRoute as HealthServerRouteImport } from './routes/health'

const rootServerRouteImport = createServerRootRoute()

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoresRoute = CountryCodeStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeResetPasswordRoute =
  CountryCodeResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeRegisterRoute = CountryCodeRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeLoginRoute = CountryCodeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeSlugRoute = CountryCodeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorsIndexRoute = CountryCodeVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorIndexRoute = CountryCodeVendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeSubscriptionsIndexRoute =
  CountryCodeSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeQuotesIndexRoute = CountryCodeQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeBookingsIndexRoute =
  CountryCodeBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountIndexRoute = CountryCodeAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorsHandleRoute =
  CountryCodeVendorsHandleRouteImport.update({
    id: '/vendors/$handle',
    path: '/vendors/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorRegisterRoute =
  CountryCodeVendorRegisterRouteImport.update({
    id: '/vendor/register',
    path: '/vendor/register',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorPayoutsRoute =
  CountryCodeVendorPayoutsRouteImport.update({
    id: '/vendor/payouts',
    path: '/vendor/payouts',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorCommissionsRoute =
  CountryCodeVendorCommissionsRouteImport.update({
    id: '/vendor/commissions',
    path: '/vendor/commissions',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeSubscriptionsSuccessRoute =
  CountryCodeSubscriptionsSuccessRouteImport.update({
    id: '/subscriptions/success',
    path: '/subscriptions/success',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeSubscriptionsCheckoutRoute =
  CountryCodeSubscriptionsCheckoutRouteImport.update({
    id: '/subscriptions/checkout',
    path: '/subscriptions/checkout',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeQuotesRequestRoute =
  CountryCodeQuotesRequestRouteImport.update({
    id: '/quotes/request',
    path: '/quotes/request',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeQuotesIdRoute = CountryCodeQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeBookingsConfirmationRoute =
  CountryCodeBookingsConfirmationRouteImport.update({
    id: '/bookings/confirmation',
    path: '/bookings/confirmation',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeBookingsServiceHandleRoute =
  CountryCodeBookingsServiceHandleRouteImport.update({
    id: '/bookings/$serviceHandle',
    path: '/bookings/$serviceHandle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeB2bRegisterRoute = CountryCodeB2bRegisterRouteImport.update({
  id: '/b2b/register',
  path: '/b2b/register',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeB2bDashboardRoute = CountryCodeB2bDashboardRouteImport.update({
  id: '/b2b/dashboard',
  path: '/b2b/dashboard',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountSettingsRoute =
  CountryCodeAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountProfileRoute =
  CountryCodeAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountAddressesRoute =
  CountryCodeAccountAddressesRouteImport.update({
    id: '/account/addresses',
    path: '/account/addresses',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorProductsIndexRoute =
  CountryCodeVendorProductsIndexRouteImport.update({
    id: '/vendor/products/',
    path: '/vendor/products/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorPayoutsIndexRoute =
  CountryCodeVendorPayoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryCodeVendorPayoutsRoute,
  } as any)
const CountryCodeVendorOrdersIndexRoute =
  CountryCodeVendorOrdersIndexRouteImport.update({
    id: '/vendor/orders/',
    path: '/vendor/orders/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountSubscriptionsIndexRoute =
  CountryCodeAccountSubscriptionsIndexRouteImport.update({
    id: '/account/subscriptions/',
    path: '/account/subscriptions/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersIndexRoute =
  CountryCodeAccountOrdersIndexRouteImport.update({
    id: '/account/orders/',
    path: '/account/orders/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountBookingsIndexRoute =
  CountryCodeAccountBookingsIndexRouteImport.update({
    id: '/account/bookings/',
    path: '/account/bookings/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorProductsNewRoute =
  CountryCodeVendorProductsNewRouteImport.update({
    id: '/vendor/products/new',
    path: '/vendor/products/new',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeVendorProductsProductIdRoute =
  CountryCodeVendorProductsProductIdRouteImport.update({
    id: '/vendor/products/$productId',
    path: '/vendor/products/$productId',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountSubscriptionsIdRoute =
  CountryCodeAccountSubscriptionsIdRouteImport.update({
    id: '/account/subscriptions/$id',
    path: '/account/subscriptions/$id',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersIdRoute =
  CountryCodeAccountOrdersIdRouteImport.update({
    id: '/account/orders/$id',
    path: '/account/orders/$id',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountBookingsIdRoute =
  CountryCodeAccountBookingsIdRouteImport.update({
    id: '/account/bookings/$id',
    path: '/account/bookings/$id',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const HealthServerRoute = HealthServerRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/store': typeof StoreRoute
  '/$countryCode/$slug': typeof CountryCodeSlugRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/login': typeof CountryCodeLoginRoute
  '/$countryCode/register': typeof CountryCodeRegisterRoute
  '/$countryCode/reset-password': typeof CountryCodeResetPasswordRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/account/settings': typeof CountryCodeAccountSettingsRoute
  '/$countryCode/b2b/dashboard': typeof CountryCodeB2bDashboardRoute
  '/$countryCode/b2b/register': typeof CountryCodeB2bRegisterRoute
  '/$countryCode/bookings/$serviceHandle': typeof CountryCodeBookingsServiceHandleRoute
  '/$countryCode/bookings/confirmation': typeof CountryCodeBookingsConfirmationRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quotes/$id': typeof CountryCodeQuotesIdRoute
  '/$countryCode/quotes/request': typeof CountryCodeQuotesRequestRoute
  '/$countryCode/subscriptions/checkout': typeof CountryCodeSubscriptionsCheckoutRoute
  '/$countryCode/subscriptions/success': typeof CountryCodeSubscriptionsSuccessRoute
  '/$countryCode/vendor/commissions': typeof CountryCodeVendorCommissionsRoute
  '/$countryCode/vendor/payouts': typeof CountryCodeVendorPayoutsRouteWithChildren
  '/$countryCode/vendor/register': typeof CountryCodeVendorRegisterRoute
  '/$countryCode/vendors/$handle': typeof CountryCodeVendorsHandleRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/bookings': typeof CountryCodeBookingsIndexRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesIndexRoute
  '/$countryCode/subscriptions': typeof CountryCodeSubscriptionsIndexRoute
  '/$countryCode/vendor': typeof CountryCodeVendorIndexRoute
  '/$countryCode/vendors': typeof CountryCodeVendorsIndexRoute
  '/$countryCode/account/bookings/$id': typeof CountryCodeAccountBookingsIdRoute
  '/$countryCode/account/orders/$id': typeof CountryCodeAccountOrdersIdRoute
  '/$countryCode/account/subscriptions/$id': typeof CountryCodeAccountSubscriptionsIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/vendor/products/$productId': typeof CountryCodeVendorProductsProductIdRoute
  '/$countryCode/vendor/products/new': typeof CountryCodeVendorProductsNewRoute
  '/$countryCode/account/bookings': typeof CountryCodeAccountBookingsIndexRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersIndexRoute
  '/$countryCode/account/subscriptions': typeof CountryCodeAccountSubscriptionsIndexRoute
  '/$countryCode/vendor/orders': typeof CountryCodeVendorOrdersIndexRoute
  '/$countryCode/vendor/payouts/': typeof CountryCodeVendorPayoutsIndexRoute
  '/$countryCode/vendor/products': typeof CountryCodeVendorProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/store': typeof StoreRoute
  '/$countryCode/$slug': typeof CountryCodeSlugRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/login': typeof CountryCodeLoginRoute
  '/$countryCode/register': typeof CountryCodeRegisterRoute
  '/$countryCode/reset-password': typeof CountryCodeResetPasswordRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/account/settings': typeof CountryCodeAccountSettingsRoute
  '/$countryCode/b2b/dashboard': typeof CountryCodeB2bDashboardRoute
  '/$countryCode/b2b/register': typeof CountryCodeB2bRegisterRoute
  '/$countryCode/bookings/$serviceHandle': typeof CountryCodeBookingsServiceHandleRoute
  '/$countryCode/bookings/confirmation': typeof CountryCodeBookingsConfirmationRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quotes/$id': typeof CountryCodeQuotesIdRoute
  '/$countryCode/quotes/request': typeof CountryCodeQuotesRequestRoute
  '/$countryCode/subscriptions/checkout': typeof CountryCodeSubscriptionsCheckoutRoute
  '/$countryCode/subscriptions/success': typeof CountryCodeSubscriptionsSuccessRoute
  '/$countryCode/vendor/commissions': typeof CountryCodeVendorCommissionsRoute
  '/$countryCode/vendor/register': typeof CountryCodeVendorRegisterRoute
  '/$countryCode/vendors/$handle': typeof CountryCodeVendorsHandleRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/bookings': typeof CountryCodeBookingsIndexRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesIndexRoute
  '/$countryCode/subscriptions': typeof CountryCodeSubscriptionsIndexRoute
  '/$countryCode/vendor': typeof CountryCodeVendorIndexRoute
  '/$countryCode/vendors': typeof CountryCodeVendorsIndexRoute
  '/$countryCode/account/bookings/$id': typeof CountryCodeAccountBookingsIdRoute
  '/$countryCode/account/orders/$id': typeof CountryCodeAccountOrdersIdRoute
  '/$countryCode/account/subscriptions/$id': typeof CountryCodeAccountSubscriptionsIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/vendor/products/$productId': typeof CountryCodeVendorProductsProductIdRoute
  '/$countryCode/vendor/products/new': typeof CountryCodeVendorProductsNewRoute
  '/$countryCode/account/bookings': typeof CountryCodeAccountBookingsIndexRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersIndexRoute
  '/$countryCode/account/subscriptions': typeof CountryCodeAccountSubscriptionsIndexRoute
  '/$countryCode/vendor/orders': typeof CountryCodeVendorOrdersIndexRoute
  '/$countryCode/vendor/payouts': typeof CountryCodeVendorPayoutsIndexRoute
  '/$countryCode/vendor/products': typeof CountryCodeVendorProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/store': typeof StoreRoute
  '/$countryCode/$slug': typeof CountryCodeSlugRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/login': typeof CountryCodeLoginRoute
  '/$countryCode/register': typeof CountryCodeRegisterRoute
  '/$countryCode/reset-password': typeof CountryCodeResetPasswordRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/account/settings': typeof CountryCodeAccountSettingsRoute
  '/$countryCode/b2b/dashboard': typeof CountryCodeB2bDashboardRoute
  '/$countryCode/b2b/register': typeof CountryCodeB2bRegisterRoute
  '/$countryCode/bookings/$serviceHandle': typeof CountryCodeBookingsServiceHandleRoute
  '/$countryCode/bookings/confirmation': typeof CountryCodeBookingsConfirmationRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/quotes/$id': typeof CountryCodeQuotesIdRoute
  '/$countryCode/quotes/request': typeof CountryCodeQuotesRequestRoute
  '/$countryCode/subscriptions/checkout': typeof CountryCodeSubscriptionsCheckoutRoute
  '/$countryCode/subscriptions/success': typeof CountryCodeSubscriptionsSuccessRoute
  '/$countryCode/vendor/commissions': typeof CountryCodeVendorCommissionsRoute
  '/$countryCode/vendor/payouts': typeof CountryCodeVendorPayoutsRouteWithChildren
  '/$countryCode/vendor/register': typeof CountryCodeVendorRegisterRoute
  '/$countryCode/vendors/$handle': typeof CountryCodeVendorsHandleRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/bookings/': typeof CountryCodeBookingsIndexRoute
  '/$countryCode/quotes/': typeof CountryCodeQuotesIndexRoute
  '/$countryCode/subscriptions/': typeof CountryCodeSubscriptionsIndexRoute
  '/$countryCode/vendor/': typeof CountryCodeVendorIndexRoute
  '/$countryCode/vendors/': typeof CountryCodeVendorsIndexRoute
  '/$countryCode/account/bookings/$id': typeof CountryCodeAccountBookingsIdRoute
  '/$countryCode/account/orders/$id': typeof CountryCodeAccountOrdersIdRoute
  '/$countryCode/account/subscriptions/$id': typeof CountryCodeAccountSubscriptionsIdRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/vendor/products/$productId': typeof CountryCodeVendorProductsProductIdRoute
  '/$countryCode/vendor/products/new': typeof CountryCodeVendorProductsNewRoute
  '/$countryCode/account/bookings/': typeof CountryCodeAccountBookingsIndexRoute
  '/$countryCode/account/orders/': typeof CountryCodeAccountOrdersIndexRoute
  '/$countryCode/account/subscriptions/': typeof CountryCodeAccountSubscriptionsIndexRoute
  '/$countryCode/vendor/orders/': typeof CountryCodeVendorOrdersIndexRoute
  '/$countryCode/vendor/payouts/': typeof CountryCodeVendorPayoutsIndexRoute
  '/$countryCode/vendor/products/': typeof CountryCodeVendorProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/store'
    | '/$countryCode/$slug'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/login'
    | '/$countryCode/register'
    | '/$countryCode/reset-password'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/account/settings'
    | '/$countryCode/b2b/dashboard'
    | '/$countryCode/b2b/register'
    | '/$countryCode/bookings/$serviceHandle'
    | '/$countryCode/bookings/confirmation'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quotes/$id'
    | '/$countryCode/quotes/request'
    | '/$countryCode/subscriptions/checkout'
    | '/$countryCode/subscriptions/success'
    | '/$countryCode/vendor/commissions'
    | '/$countryCode/vendor/payouts'
    | '/$countryCode/vendor/register'
    | '/$countryCode/vendors/$handle'
    | '/$countryCode/account'
    | '/$countryCode/bookings'
    | '/$countryCode/quotes'
    | '/$countryCode/subscriptions'
    | '/$countryCode/vendor'
    | '/$countryCode/vendors'
    | '/$countryCode/account/bookings/$id'
    | '/$countryCode/account/orders/$id'
    | '/$countryCode/account/subscriptions/$id'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/vendor/products/$productId'
    | '/$countryCode/vendor/products/new'
    | '/$countryCode/account/bookings'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/subscriptions'
    | '/$countryCode/vendor/orders'
    | '/$countryCode/vendor/payouts/'
    | '/$countryCode/vendor/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/store'
    | '/$countryCode/$slug'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/login'
    | '/$countryCode/register'
    | '/$countryCode/reset-password'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/account/settings'
    | '/$countryCode/b2b/dashboard'
    | '/$countryCode/b2b/register'
    | '/$countryCode/bookings/$serviceHandle'
    | '/$countryCode/bookings/confirmation'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quotes/$id'
    | '/$countryCode/quotes/request'
    | '/$countryCode/subscriptions/checkout'
    | '/$countryCode/subscriptions/success'
    | '/$countryCode/vendor/commissions'
    | '/$countryCode/vendor/register'
    | '/$countryCode/vendors/$handle'
    | '/$countryCode/account'
    | '/$countryCode/bookings'
    | '/$countryCode/quotes'
    | '/$countryCode/subscriptions'
    | '/$countryCode/vendor'
    | '/$countryCode/vendors'
    | '/$countryCode/account/bookings/$id'
    | '/$countryCode/account/orders/$id'
    | '/$countryCode/account/subscriptions/$id'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/vendor/products/$productId'
    | '/$countryCode/vendor/products/new'
    | '/$countryCode/account/bookings'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/subscriptions'
    | '/$countryCode/vendor/orders'
    | '/$countryCode/vendor/payouts'
    | '/$countryCode/vendor/products'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/store'
    | '/$countryCode/$slug'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/login'
    | '/$countryCode/register'
    | '/$countryCode/reset-password'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/account/settings'
    | '/$countryCode/b2b/dashboard'
    | '/$countryCode/b2b/register'
    | '/$countryCode/bookings/$serviceHandle'
    | '/$countryCode/bookings/confirmation'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/quotes/$id'
    | '/$countryCode/quotes/request'
    | '/$countryCode/subscriptions/checkout'
    | '/$countryCode/subscriptions/success'
    | '/$countryCode/vendor/commissions'
    | '/$countryCode/vendor/payouts'
    | '/$countryCode/vendor/register'
    | '/$countryCode/vendors/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/bookings/'
    | '/$countryCode/quotes/'
    | '/$countryCode/subscriptions/'
    | '/$countryCode/vendor/'
    | '/$countryCode/vendors/'
    | '/$countryCode/account/bookings/$id'
    | '/$countryCode/account/orders/$id'
    | '/$countryCode/account/subscriptions/$id'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/vendor/products/$productId'
    | '/$countryCode/vendor/products/new'
    | '/$countryCode/account/bookings/'
    | '/$countryCode/account/orders/'
    | '/$countryCode/account/subscriptions/'
    | '/$countryCode/vendor/orders/'
    | '/$countryCode/vendor/payouts/'
    | '/$countryCode/vendor/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  StoreRoute: typeof StoreRoute
}
export interface FileServerRoutesByFullPath {
  '/health': typeof HealthServerRoute
}
export interface FileServerRoutesByTo {
  '/health': typeof HealthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/health': typeof HealthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/health'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/health'
  id: '__root__' | '/health'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  HealthServerRoute: typeof HealthServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/stores': {
      id: '/$countryCode/stores'
      path: '/stores'
      fullPath: '/$countryCode/stores'
      preLoaderRoute: typeof CountryCodeStoresRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/reset-password': {
      id: '/$countryCode/reset-password'
      path: '/reset-password'
      fullPath: '/$countryCode/reset-password'
      preLoaderRoute: typeof CountryCodeResetPasswordRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/register': {
      id: '/$countryCode/register'
      path: '/register'
      fullPath: '/$countryCode/register'
      preLoaderRoute: typeof CountryCodeRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/login': {
      id: '/$countryCode/login'
      path: '/login'
      fullPath: '/$countryCode/login'
      preLoaderRoute: typeof CountryCodeLoginRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/$slug': {
      id: '/$countryCode/$slug'
      path: '/$slug'
      fullPath: '/$countryCode/$slug'
      preLoaderRoute: typeof CountryCodeSlugRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendors/': {
      id: '/$countryCode/vendors/'
      path: '/vendors'
      fullPath: '/$countryCode/vendors'
      preLoaderRoute: typeof CountryCodeVendorsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/': {
      id: '/$countryCode/vendor/'
      path: '/vendor'
      fullPath: '/$countryCode/vendor'
      preLoaderRoute: typeof CountryCodeVendorIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/subscriptions/': {
      id: '/$countryCode/subscriptions/'
      path: '/subscriptions'
      fullPath: '/$countryCode/subscriptions'
      preLoaderRoute: typeof CountryCodeSubscriptionsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes/': {
      id: '/$countryCode/quotes/'
      path: '/quotes'
      fullPath: '/$countryCode/quotes'
      preLoaderRoute: typeof CountryCodeQuotesIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/bookings/': {
      id: '/$countryCode/bookings/'
      path: '/bookings'
      fullPath: '/$countryCode/bookings'
      preLoaderRoute: typeof CountryCodeBookingsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/': {
      id: '/$countryCode/account/'
      path: '/account'
      fullPath: '/$countryCode/account'
      preLoaderRoute: typeof CountryCodeAccountIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendors/$handle': {
      id: '/$countryCode/vendors/$handle'
      path: '/vendors/$handle'
      fullPath: '/$countryCode/vendors/$handle'
      preLoaderRoute: typeof CountryCodeVendorsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/register': {
      id: '/$countryCode/vendor/register'
      path: '/vendor/register'
      fullPath: '/$countryCode/vendor/register'
      preLoaderRoute: typeof CountryCodeVendorRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/payouts': {
      id: '/$countryCode/vendor/payouts'
      path: '/vendor/payouts'
      fullPath: '/$countryCode/vendor/payouts'
      preLoaderRoute: typeof CountryCodeVendorPayoutsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/commissions': {
      id: '/$countryCode/vendor/commissions'
      path: '/vendor/commissions'
      fullPath: '/$countryCode/vendor/commissions'
      preLoaderRoute: typeof CountryCodeVendorCommissionsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/subscriptions/success': {
      id: '/$countryCode/subscriptions/success'
      path: '/subscriptions/success'
      fullPath: '/$countryCode/subscriptions/success'
      preLoaderRoute: typeof CountryCodeSubscriptionsSuccessRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/subscriptions/checkout': {
      id: '/$countryCode/subscriptions/checkout'
      path: '/subscriptions/checkout'
      fullPath: '/$countryCode/subscriptions/checkout'
      preLoaderRoute: typeof CountryCodeSubscriptionsCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes/request': {
      id: '/$countryCode/quotes/request'
      path: '/quotes/request'
      fullPath: '/$countryCode/quotes/request'
      preLoaderRoute: typeof CountryCodeQuotesRequestRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes/$id': {
      id: '/$countryCode/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/$countryCode/quotes/$id'
      preLoaderRoute: typeof CountryCodeQuotesIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/bookings/confirmation': {
      id: '/$countryCode/bookings/confirmation'
      path: '/bookings/confirmation'
      fullPath: '/$countryCode/bookings/confirmation'
      preLoaderRoute: typeof CountryCodeBookingsConfirmationRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/bookings/$serviceHandle': {
      id: '/$countryCode/bookings/$serviceHandle'
      path: '/bookings/$serviceHandle'
      fullPath: '/$countryCode/bookings/$serviceHandle'
      preLoaderRoute: typeof CountryCodeBookingsServiceHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/b2b/register': {
      id: '/$countryCode/b2b/register'
      path: '/b2b/register'
      fullPath: '/$countryCode/b2b/register'
      preLoaderRoute: typeof CountryCodeB2bRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/b2b/dashboard': {
      id: '/$countryCode/b2b/dashboard'
      path: '/b2b/dashboard'
      fullPath: '/$countryCode/b2b/dashboard'
      preLoaderRoute: typeof CountryCodeB2bDashboardRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/settings': {
      id: '/$countryCode/account/settings'
      path: '/account/settings'
      fullPath: '/$countryCode/account/settings'
      preLoaderRoute: typeof CountryCodeAccountSettingsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/profile': {
      id: '/$countryCode/account/profile'
      path: '/account/profile'
      fullPath: '/$countryCode/account/profile'
      preLoaderRoute: typeof CountryCodeAccountProfileRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/addresses': {
      id: '/$countryCode/account/addresses'
      path: '/account/addresses'
      fullPath: '/$countryCode/account/addresses'
      preLoaderRoute: typeof CountryCodeAccountAddressesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/products/': {
      id: '/$countryCode/vendor/products/'
      path: '/vendor/products'
      fullPath: '/$countryCode/vendor/products'
      preLoaderRoute: typeof CountryCodeVendorProductsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/payouts/': {
      id: '/$countryCode/vendor/payouts/'
      path: '/'
      fullPath: '/$countryCode/vendor/payouts/'
      preLoaderRoute: typeof CountryCodeVendorPayoutsIndexRouteImport
      parentRoute: typeof CountryCodeVendorPayoutsRoute
    }
    '/$countryCode/vendor/orders/': {
      id: '/$countryCode/vendor/orders/'
      path: '/vendor/orders'
      fullPath: '/$countryCode/vendor/orders'
      preLoaderRoute: typeof CountryCodeVendorOrdersIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/subscriptions/': {
      id: '/$countryCode/account/subscriptions/'
      path: '/account/subscriptions'
      fullPath: '/$countryCode/account/subscriptions'
      preLoaderRoute: typeof CountryCodeAccountSubscriptionsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders/': {
      id: '/$countryCode/account/orders/'
      path: '/account/orders'
      fullPath: '/$countryCode/account/orders'
      preLoaderRoute: typeof CountryCodeAccountOrdersIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/bookings/': {
      id: '/$countryCode/account/bookings/'
      path: '/account/bookings'
      fullPath: '/$countryCode/account/bookings'
      preLoaderRoute: typeof CountryCodeAccountBookingsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/products/new': {
      id: '/$countryCode/vendor/products/new'
      path: '/vendor/products/new'
      fullPath: '/$countryCode/vendor/products/new'
      preLoaderRoute: typeof CountryCodeVendorProductsNewRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendor/products/$productId': {
      id: '/$countryCode/vendor/products/$productId'
      path: '/vendor/products/$productId'
      fullPath: '/$countryCode/vendor/products/$productId'
      preLoaderRoute: typeof CountryCodeVendorProductsProductIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/subscriptions/$id': {
      id: '/$countryCode/account/subscriptions/$id'
      path: '/account/subscriptions/$id'
      fullPath: '/$countryCode/account/subscriptions/$id'
      preLoaderRoute: typeof CountryCodeAccountSubscriptionsIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders/$id': {
      id: '/$countryCode/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/$countryCode/account/orders/$id'
      preLoaderRoute: typeof CountryCodeAccountOrdersIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/bookings/$id': {
      id: '/$countryCode/account/bookings/$id'
      path: '/account/bookings/$id'
      fullPath: '/$countryCode/account/bookings/$id'
      preLoaderRoute: typeof CountryCodeAccountBookingsIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface CountryCodeVendorPayoutsRouteChildren {
  CountryCodeVendorPayoutsIndexRoute: typeof CountryCodeVendorPayoutsIndexRoute
}

const CountryCodeVendorPayoutsRouteChildren: CountryCodeVendorPayoutsRouteChildren =
  {
    CountryCodeVendorPayoutsIndexRoute: CountryCodeVendorPayoutsIndexRoute,
  }

const CountryCodeVendorPayoutsRouteWithChildren =
  CountryCodeVendorPayoutsRoute._addFileChildren(
    CountryCodeVendorPayoutsRouteChildren,
  )

interface CountryCodeRouteChildren {
  CountryCodeSlugRoute: typeof CountryCodeSlugRoute
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeLoginRoute: typeof CountryCodeLoginRoute
  CountryCodeRegisterRoute: typeof CountryCodeRegisterRoute
  CountryCodeResetPasswordRoute: typeof CountryCodeResetPasswordRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeStoresRoute: typeof CountryCodeStoresRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeAccountAddressesRoute: typeof CountryCodeAccountAddressesRoute
  CountryCodeAccountProfileRoute: typeof CountryCodeAccountProfileRoute
  CountryCodeAccountSettingsRoute: typeof CountryCodeAccountSettingsRoute
  CountryCodeB2bDashboardRoute: typeof CountryCodeB2bDashboardRoute
  CountryCodeB2bRegisterRoute: typeof CountryCodeB2bRegisterRoute
  CountryCodeBookingsServiceHandleRoute: typeof CountryCodeBookingsServiceHandleRoute
  CountryCodeBookingsConfirmationRoute: typeof CountryCodeBookingsConfirmationRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeQuotesIdRoute: typeof CountryCodeQuotesIdRoute
  CountryCodeQuotesRequestRoute: typeof CountryCodeQuotesRequestRoute
  CountryCodeSubscriptionsCheckoutRoute: typeof CountryCodeSubscriptionsCheckoutRoute
  CountryCodeSubscriptionsSuccessRoute: typeof CountryCodeSubscriptionsSuccessRoute
  CountryCodeVendorCommissionsRoute: typeof CountryCodeVendorCommissionsRoute
  CountryCodeVendorPayoutsRoute: typeof CountryCodeVendorPayoutsRouteWithChildren
  CountryCodeVendorRegisterRoute: typeof CountryCodeVendorRegisterRoute
  CountryCodeVendorsHandleRoute: typeof CountryCodeVendorsHandleRoute
  CountryCodeAccountIndexRoute: typeof CountryCodeAccountIndexRoute
  CountryCodeBookingsIndexRoute: typeof CountryCodeBookingsIndexRoute
  CountryCodeQuotesIndexRoute: typeof CountryCodeQuotesIndexRoute
  CountryCodeSubscriptionsIndexRoute: typeof CountryCodeSubscriptionsIndexRoute
  CountryCodeVendorIndexRoute: typeof CountryCodeVendorIndexRoute
  CountryCodeVendorsIndexRoute: typeof CountryCodeVendorsIndexRoute
  CountryCodeAccountBookingsIdRoute: typeof CountryCodeAccountBookingsIdRoute
  CountryCodeAccountOrdersIdRoute: typeof CountryCodeAccountOrdersIdRoute
  CountryCodeAccountSubscriptionsIdRoute: typeof CountryCodeAccountSubscriptionsIdRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
  CountryCodeVendorProductsProductIdRoute: typeof CountryCodeVendorProductsProductIdRoute
  CountryCodeVendorProductsNewRoute: typeof CountryCodeVendorProductsNewRoute
  CountryCodeAccountBookingsIndexRoute: typeof CountryCodeAccountBookingsIndexRoute
  CountryCodeAccountOrdersIndexRoute: typeof CountryCodeAccountOrdersIndexRoute
  CountryCodeAccountSubscriptionsIndexRoute: typeof CountryCodeAccountSubscriptionsIndexRoute
  CountryCodeVendorOrdersIndexRoute: typeof CountryCodeVendorOrdersIndexRoute
  CountryCodeVendorProductsIndexRoute: typeof CountryCodeVendorProductsIndexRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeSlugRoute: CountryCodeSlugRoute,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeLoginRoute: CountryCodeLoginRoute,
  CountryCodeRegisterRoute: CountryCodeRegisterRoute,
  CountryCodeResetPasswordRoute: CountryCodeResetPasswordRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeStoresRoute: CountryCodeStoresRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeAccountAddressesRoute: CountryCodeAccountAddressesRoute,
  CountryCodeAccountProfileRoute: CountryCodeAccountProfileRoute,
  CountryCodeAccountSettingsRoute: CountryCodeAccountSettingsRoute,
  CountryCodeB2bDashboardRoute: CountryCodeB2bDashboardRoute,
  CountryCodeB2bRegisterRoute: CountryCodeB2bRegisterRoute,
  CountryCodeBookingsServiceHandleRoute: CountryCodeBookingsServiceHandleRoute,
  CountryCodeBookingsConfirmationRoute: CountryCodeBookingsConfirmationRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeQuotesIdRoute: CountryCodeQuotesIdRoute,
  CountryCodeQuotesRequestRoute: CountryCodeQuotesRequestRoute,
  CountryCodeSubscriptionsCheckoutRoute: CountryCodeSubscriptionsCheckoutRoute,
  CountryCodeSubscriptionsSuccessRoute: CountryCodeSubscriptionsSuccessRoute,
  CountryCodeVendorCommissionsRoute: CountryCodeVendorCommissionsRoute,
  CountryCodeVendorPayoutsRoute: CountryCodeVendorPayoutsRouteWithChildren,
  CountryCodeVendorRegisterRoute: CountryCodeVendorRegisterRoute,
  CountryCodeVendorsHandleRoute: CountryCodeVendorsHandleRoute,
  CountryCodeAccountIndexRoute: CountryCodeAccountIndexRoute,
  CountryCodeBookingsIndexRoute: CountryCodeBookingsIndexRoute,
  CountryCodeQuotesIndexRoute: CountryCodeQuotesIndexRoute,
  CountryCodeSubscriptionsIndexRoute: CountryCodeSubscriptionsIndexRoute,
  CountryCodeVendorIndexRoute: CountryCodeVendorIndexRoute,
  CountryCodeVendorsIndexRoute: CountryCodeVendorsIndexRoute,
  CountryCodeAccountBookingsIdRoute: CountryCodeAccountBookingsIdRoute,
  CountryCodeAccountOrdersIdRoute: CountryCodeAccountOrdersIdRoute,
  CountryCodeAccountSubscriptionsIdRoute:
    CountryCodeAccountSubscriptionsIdRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
  CountryCodeVendorProductsProductIdRoute:
    CountryCodeVendorProductsProductIdRoute,
  CountryCodeVendorProductsNewRoute: CountryCodeVendorProductsNewRoute,
  CountryCodeAccountBookingsIndexRoute: CountryCodeAccountBookingsIndexRoute,
  CountryCodeAccountOrdersIndexRoute: CountryCodeAccountOrdersIndexRoute,
  CountryCodeAccountSubscriptionsIndexRoute:
    CountryCodeAccountSubscriptionsIndexRoute,
  CountryCodeVendorOrdersIndexRoute: CountryCodeVendorOrdersIndexRoute,
  CountryCodeVendorProductsIndexRoute: CountryCodeVendorProductsIndexRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  HealthServerRoute: HealthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
